#!/usr/bin/env python3
"""deploy-scaffold.py — emit a systemd unit + nginx vhost + deploy.sh trio for
a single-host Django/gunicorn app behind nginx.

Every identity the host can collide on is derived from --name and printed in
the summary line: unix user/group, service unit, state dir, nginx limit_req
zone, webroot, upstream port. Two apps scaffolded with different --name values
cannot share a /var/lib directory or a rate-limit zone by accident — the
failure mode that took down a sibling deploy when both emitted the same
service name.

Input:  --name --port --domain --root  (+ optional overrides, see --help)
Output: <out-dir>/<name>.service, <out-dir>/nginx.conf, <out-dir>/deploy.sh
        one summary line on stdout.
Exit:   0 written · 1 refused (existing files, use --force) · 2 bad input ·
        3 --check-local found the identity already taken on this machine.

Zero model calls. Templates only — nothing is installed or restarted.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,30}$")
DOMAIN_RE = re.compile(r"^[a-z0-9.-]+$")

SERVICE_TMPL = """\
[Unit]
Description={domain} gunicorn ({name})
After=network.target

[Service]
User={user}
Group={group}
WorkingDirectory={root}/{backend}
EnvironmentFile={root}/.env
ExecStart={root}/.venv/bin/gunicorn {wsgi} \\
  --bind 127.0.0.1:{port} --workers {workers} --timeout 30 \\
  --max-requests 1000 --max-requests-jitter 100 \\
  --access-logfile - --error-logfile -
Restart=on-failure
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths={state_dir}

[Install]
WantedBy=multi-user.target
"""

NGINX_HEAD = """\
# {domain} server block, generated by deploy-scaffold.py.
# Install as /etc/nginx/sites-available/{domain} (symlink into sites-enabled).
# TLS via the host's existing certbot include.
#
# Identity is namespaced by '{name}': the limit_req zone is {zone}. A zone
# name reused by a second app makes nginx -t fail (duplicate zone) or, worse,
# silently share one rate-limit bucket between two unrelated services.

limit_req_zone $binary_remote_addr zone={zone}:10m rate={rate};

server {{
  listen 443 ssl http2;
  server_name {domain};
  # ssl_certificate ... via existing certbot include

  root {webroot};
  etag on;

  location /api/ {{
    limit_req zone={zone} burst={burst} nodelay;
    client_max_body_size 16k;
    proxy_pass http://127.0.0.1:{port};
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_read_timeout 35s;
  }}
"""

NGINX_TAIL = """\
  location / {{ try_files $uri $uri/ =404; expires 5m; }}
}}

server {{
  listen 80;
  server_name {domain};
  return 301 https://$host$request_uri;
}}
"""

DEPLOY_TMPL = """\
#!/usr/bin/env bash
# Deploy {domain} — generated by deploy-scaffold.py.
# Flow: local test gate -> rsync -> pip install -> migrate + remote test gate
#       (abort on red) -> restart service -> rsync frontend -> edge smoke.
#
# First-time provisioning on the host:
#   1. sudo useradd --system --create-home --home-dir {root} {user}
#   2. rsync the repo -> {root} (this script) + sudo chown -R {user}:{group} {root}
#   3. sudo -u {user} python3 -m venv {root}/.venv
#   4. {root}/.env (0600, {user}:{group}) — generate SECRET_KEY ON THE HOST:
#        SECRET_KEY=$(python3 -c 'import secrets;print(secrets.token_urlsafe(50))')
#        DEBUG=0  ALLOWED_HOSTS={domain}
#   5. sudo mkdir -p {state_dir} && sudo chown -R {user}:{group} {state_dir} \\
#        && sudo chmod 0750 {state_dir}
#   6. sudo cp deploy/{name}.service /etc/systemd/system/ \\
#        && sudo systemctl daemon-reload && sudo systemctl enable --now {name}
#   7. sudo cp deploy/nginx.conf /etc/nginx/sites-available/{domain} \\
#        && sudo ln -sf /etc/nginx/sites-available/{domain} /etc/nginx/sites-enabled/ \\
#        && sudo nginx -t && sudo systemctl reload nginx
set -euo pipefail

SSH_KEY="${{SSH_KEY:-{ssh_key}}}"
REMOTE="{ssh_user}@{ssh_addr}"
PORT={ssh_port}
# accept-new, never `no` with /dev/null: the latter accepts any key every run
SSH="ssh -i $SSH_KEY -p $PORT -o StrictHostKeyChecking=accept-new"
APP_DIR="{root}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "== local deploy gate"
(cd "$REPO_ROOT/{backend}" && "$REPO_ROOT/.venv/bin/python" manage.py test {test_labels})

echo "== check ssh reachability"
$SSH "$REMOTE" true

echo "== rsync code"
# plain --delete, never --delete-excluded: the latter wipes .venv/.env on the host
rsync -a --delete \\
  --exclude .git --exclude .venv --exclude __pycache__ --exclude '*.pyc' \\
  --exclude '*.sqlite3' --exclude '*.sqlite3-wal' --exclude '*.sqlite3-shm' \\
  --exclude .env \\
  -e "$SSH" \\
  --rsync-path="sudo rsync" \\
  "$REPO_ROOT/" "$REMOTE:$APP_DIR/"

echo "== remote install + gate + restart"
$SSH "$REMOTE" "
  set -euo pipefail
  sudo chown -R {user}:{group} $APP_DIR
  sudo -u {user} $APP_DIR/.venv/bin/pip install -q -r $APP_DIR/{backend}/requirements.txt
  sudo -u {user} bash -c 'set -a; source $APP_DIR/.env; set +a; cd $APP_DIR/{backend} &&
    ../.venv/bin/python manage.py migrate &&
    ../.venv/bin/python manage.py test {test_labels}'
  sudo systemctl restart {name}
  sudo rsync -a --delete $APP_DIR/{frontend}/ {webroot}/
  sudo chown -R www-data:www-data {webroot}
"

echo "== edge smoke"
curl -fsS -o /dev/null -w 'https://{domain}/ -> %{{http_code}}\\n' https://{domain}/
curl -fsS -o /dev/null -w 'https://{domain}/api/health -> %{{http_code}}\\n' https://{domain}/api/health

echo "== done: https://{domain}"
"""


def parse_route(spec: str, kind: str) -> tuple[str, str]:
    pattern, sep, target = spec.partition("=")
    if not sep or not pattern or not target:
        raise ValueError(f"--{kind}-route must be 'PATTERN=FILE', got {spec!r}")
    return pattern, target


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", required=True, help="service identity, [a-z][a-z0-9-]+")
    ap.add_argument("--port", required=True, type=int, help="gunicorn loopback port")
    ap.add_argument("--domain", required=True, help="public hostname")
    ap.add_argument("--root", required=True, help="app dir on the host, e.g. /opt/<name>")
    ap.add_argument("--out-dir", default="deploy", help="where to write the trio (default deploy/)")
    ap.add_argument("--wsgi", help="wsgi target (default <name>.wsgi:application)")
    ap.add_argument("--user", help="unix user (default <name>)")
    ap.add_argument("--group", help="unix group (default = user)")
    ap.add_argument("--state-dir", help="writable state dir (default /var/lib/<name>)")
    ap.add_argument("--webroot", help="static root (default /var/www/<domain>)")
    ap.add_argument("--zone", help="nginx limit_req zone (default <name>api)")
    ap.add_argument("--backend", default="backend", help="backend subdir (default backend)")
    ap.add_argument("--frontend", default="frontend", help="frontend subdir (default frontend)")
    ap.add_argument("--test-labels", default="", help="labels for the deploy test gate")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--rate", default="10r/s")
    ap.add_argument("--burst", type=int, default=20)
    ap.add_argument("--ssh-user", required=True,
                    help="deploy user on the target host")
    ap.add_argument("--ssh-addr", required=True,
                    help="target host address; no default — a wrong one deploys to a stranger")
    ap.add_argument("--ssh-port", type=int, default=22)
    ap.add_argument("--ssh-key", default="~/.ssh/id_ed25519",
                    help="private key for the deploy user; SSH_KEY env overrides at run time")
    ap.add_argument("--page-route", action="append", default=[], metavar="PATH=FILE",
                    help="exact location, e.g. /dashboard=dashboard.html (repeatable)")
    ap.add_argument("--regex-route", action="append", default=[], metavar="REGEX=FILE",
                    help="regex location, always emitted quoted (repeatable)")
    ap.add_argument("--check-local", action="store_true",
                    help="fail with exit 3 if this identity already exists on this machine")
    ap.add_argument("--force", action="store_true", help="overwrite existing output files")
    args = ap.parse_args()

    if not NAME_RE.match(args.name):
        print(f"deploy-scaffold: --name must match {NAME_RE.pattern}", file=sys.stderr)
        return 2
    if not DOMAIN_RE.match(args.domain):
        print("deploy-scaffold: --domain must be a bare hostname", file=sys.stderr)
        return 2
    if not 1024 <= args.port <= 65535:
        print("deploy-scaffold: --port must be 1024-65535", file=sys.stderr)
        return 2

    name = args.name
    user = args.user or name
    group = args.group or user
    state_dir = args.state_dir or f"/var/lib/{name}"
    webroot = args.webroot or f"/var/www/{args.domain}"
    zone = args.zone or f"{name}api"
    wsgi = args.wsgi or f"{name}.wsgi:application"

    if args.check_local:
        taken = []
        if Path(f"/etc/systemd/system/{name}.service").exists():
            taken.append(f"/etc/systemd/system/{name}.service")
        if Path(state_dir).exists():
            taken.append(state_dir)
        if Path(f"/etc/nginx/sites-available/{args.domain}").exists():
            taken.append(f"/etc/nginx/sites-available/{args.domain}")
        if taken:
            print("deploy-scaffold: identity already taken: " + ", ".join(taken),
                  file=sys.stderr)
            return 3

    try:
        pages = [parse_route(s, "page") for s in args.page_route]
        regexes = [parse_route(s, "regex") for s in args.regex_route]
    except ValueError as exc:
        print(f"deploy-scaffold: {exc}", file=sys.stderr)
        return 2

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    targets = {
        out / f"{name}.service": SERVICE_TMPL.format(
            name=name, domain=args.domain, user=user, group=group, root=args.root,
            backend=args.backend, wsgi=wsgi, port=args.port, workers=args.workers,
            state_dir=state_dir),
        out / "deploy.sh": DEPLOY_TMPL.format(
            name=name, domain=args.domain, user=user, group=group, root=args.root,
            backend=args.backend, frontend=args.frontend, webroot=webroot,
            state_dir=state_dir, test_labels=args.test_labels,
            ssh_user=args.ssh_user, ssh_addr=args.ssh_addr,
            ssh_port=args.ssh_port, ssh_key=args.ssh_key),
    }

    body = NGINX_HEAD.format(name=name, domain=args.domain, zone=zone, rate=args.rate,
                             burst=args.burst, port=args.port, webroot=webroot)
    if regexes:
        body += ("\n  # A regex containing {n} MUST be quoted — unquoted, nginx parses\n"
                 "  # '{' as a block open and the whole config fails nginx -t.\n")
        for pattern, target in regexes:
            body += f'  location ~ "{pattern}" {{ try_files /{target} =404; }}\n'
    if pages:
        body += "\n"
        for pattern, target in pages:
            body += f"  location = {pattern} {{ try_files /{target} =404; }}\n"
    body += "\n" + NGINX_TAIL.format(domain=args.domain)
    targets[out / "nginx.conf"] = body

    existing = [p.name for p in targets if p.exists()]
    if existing and not args.force:
        print(f"deploy-scaffold: refusing to overwrite {', '.join(sorted(existing))} "
              f"in {out} (use --force)", file=sys.stderr)
        return 1

    for path, text in targets.items():
        path.write_text(text, encoding="utf-8")
    (out / "deploy.sh").chmod(0o755)

    print(f"deploy-scaffold: name={name} service={name}.service user={user}:{group} "
          f"port={args.port} zone={zone} state={state_dir} webroot={webroot} "
          f"-> {out}/{{{name}.service,nginx.conf,deploy.sh}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
