#!/usr/bin/env python3
"""deploy-scaffold.py — emit a systemd unit + nginx vhost + deploy.sh trio for
a single-host Django/gunicorn app behind nginx.

Every identity the host can collide on is derived from --name and printed in
the summary line: unix user/group, service unit, state dir, nginx limit_req
zone, webroot, upstream port. Two apps scaffolded with different --name values
cannot share a /var/lib directory or a rate-limit zone by accident — the
failure mode that took down a sibling deploy when both emitted the same
service name.

Input:  --name --port --domain --root  (+ optional overrides, see --help)
Output: <out-dir>/<name>.service, <out-dir>/nginx.conf, <out-dir>/deploy.sh
        one summary line on stdout.
Exit:   0 written · 1 refused (existing files, use --force) · 2 bad input ·
        3 --check-local found the identity already taken on this machine.

Zero model calls. Templates only — nothing is installed or restarted.
"""
from __future__ import annotations

import argparse
import contextlib
import io
import re
import sys
import tempfile
from pathlib import Path

NAME = "deploy-scaffold"
NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,30}$")
DOMAIN_RE = re.compile(r"^[a-z0-9.-]+$")

SERVICE_TMPL = """\
[Unit]
Description={domain} gunicorn ({name})
After=network.target

[Service]
User={user}
Group={group}
WorkingDirectory={root}/{backend}
EnvironmentFile={root}/.env
ExecStart={root}/.venv/bin/gunicorn {wsgi} \\
  --bind 127.0.0.1:{port} --workers {workers} --timeout 30 \\
  --max-requests 1000 --max-requests-jitter 100 \\
  --access-logfile - --error-logfile -
Restart=on-failure
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths={state_dir}

[Install]
WantedBy=multi-user.target
"""

NGINX_HEAD = """\
# {domain} server block, generated by deploy-scaffold.py.
# Install as /etc/nginx/sites-available/{domain} (symlink into sites-enabled).
# TLS via the host's existing certbot include.
#
# Identity is namespaced by '{name}': the limit_req zone is {zone}. A zone
# name reused by a second app makes nginx -t fail (duplicate zone) or, worse,
# silently share one rate-limit bucket between two unrelated services.

limit_req_zone $binary_remote_addr zone={zone}:10m rate={rate};

server {{
  listen 443 ssl http2;
  server_name {domain};
  # ssl_certificate ... via existing certbot include

  root {webroot};
  etag on;

  location /api/ {{
    limit_req zone={zone} burst={burst} nodelay;
    client_max_body_size 16k;
    proxy_pass http://127.0.0.1:{port};
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_read_timeout 35s;
  }}
"""

NGINX_TAIL = """\
  location / {{ try_files $uri $uri/ =404; expires 5m; }}
}}

server {{
  listen 80;
  server_name {domain};
  return 301 https://$host$request_uri;
}}
"""

DEPLOY_TMPL = """\
#!/usr/bin/env bash
# Deploy {domain} — generated by deploy-scaffold.py.
# Flow: local test gate -> rsync -> pip install -> migrate + remote test gate
#       (abort on red) -> restart service -> rsync frontend -> edge smoke.
#
# First-time provisioning on the host:
#   1. sudo useradd --system --create-home --home-dir {root} {user}
#   2. rsync the repo -> {root} (this script) + sudo chown -R {user}:{group} {root}
#   3. sudo -u {user} python3 -m venv {root}/.venv
#   4. {root}/.env (0600, {user}:{group}) — generate SECRET_KEY ON THE HOST:
#        SECRET_KEY=$(python3 -c 'import secrets;print(secrets.token_urlsafe(50))')
#        DEBUG=0  ALLOWED_HOSTS={domain}
#   5. sudo mkdir -p {state_dir} && sudo chown -R {user}:{group} {state_dir} \\
#        && sudo chmod 0750 {state_dir}
#   6. sudo cp deploy/{name}.service /etc/systemd/system/ \\
#        && sudo systemctl daemon-reload && sudo systemctl enable --now {name}
#   7. sudo cp deploy/nginx.conf /etc/nginx/sites-available/{domain} \\
#        && sudo ln -sf /etc/nginx/sites-available/{domain} /etc/nginx/sites-enabled/ \\
#        && sudo nginx -t && sudo systemctl reload nginx
set -euo pipefail

SSH_KEY="${{SSH_KEY:-{ssh_key}}}"
REMOTE="{ssh_user}@{ssh_addr}"
PORT={ssh_port}
# accept-new, never `no` with /dev/null: the latter accepts any key every run
SSH="ssh -i $SSH_KEY -p $PORT -o StrictHostKeyChecking=accept-new"
APP_DIR="{root}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "== local deploy gate"
(cd "$REPO_ROOT/{backend}" && "$REPO_ROOT/.venv/bin/python" manage.py test {test_labels})

echo "== check ssh reachability"
$SSH "$REMOTE" true

echo "== rsync code"
# plain --delete, never --delete-excluded: the latter wipes .venv/.env on the host
rsync -a --delete \\
  --exclude .git --exclude .venv --exclude __pycache__ --exclude '*.pyc' \\
  --exclude '*.sqlite3' --exclude '*.sqlite3-wal' --exclude '*.sqlite3-shm' \\
  --exclude .env \\
  -e "$SSH" \\
  --rsync-path="sudo rsync" \\
  "$REPO_ROOT/" "$REMOTE:$APP_DIR/"

echo "== remote install + gate + restart"
$SSH "$REMOTE" "
  set -euo pipefail
  sudo chown -R {user}:{group} $APP_DIR
  sudo -u {user} $APP_DIR/.venv/bin/pip install -q -r $APP_DIR/{backend}/requirements.txt
  sudo -u {user} bash -c 'set -a; source $APP_DIR/.env; set +a; cd $APP_DIR/{backend} &&
    ../.venv/bin/python manage.py migrate &&
    ../.venv/bin/python manage.py test {test_labels}'
  sudo systemctl restart {name}
  sudo rsync -a --delete $APP_DIR/{frontend}/ {webroot}/
  sudo chown -R www-data:www-data {webroot}
"

echo "== edge smoke"
curl -fsS -o /dev/null -w 'https://{domain}/ -> %{{http_code}}\\n' https://{domain}/
curl -fsS -o /dev/null -w 'https://{domain}/api/health -> %{{http_code}}\\n' https://{domain}/api/health

echo "== done: https://{domain}"
"""


def parse_route(spec: str, kind: str) -> tuple[str, str]:
    pattern, sep, target = spec.partition("=")
    if not sep or not pattern or not target:
        raise ValueError(f"--{kind}-route must be 'PATTERN=FILE', got {spec!r}")
    return pattern, target


def run_cli(argv: list[str]) -> int:
    """Call main() with a fixed argv and swallow its output. --self-test uses
    this to prove the exit contract end to end rather than by inspection: the
    refusal to overwrite, the three input rejections and the taken-identity
    code all have to reach the caller as the number the card promises."""
    saved = sys.argv
    sys.argv = [NAME] + argv
    try:
        with contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            return main()
    finally:
        sys.argv = saved


def self_test() -> list[str]:
    """Prove the generator against fixtures written to a temporary directory.

    What is checked is what a wrong scaffold costs: two apps that collide on a
    host identity, an nginx regex that fails `nginx -t`, a deploy script that
    wipes the host's .env, and a rerun that silently overwrites a hand-edited
    unit. Nothing here installs, restarts or leaves the temporary directory.
    """
    failures: list[str] = []

    def read(directory: Path) -> dict[str, str]:
        return {p.name: p.read_text(encoding="utf-8")
                for p in sorted(directory.iterdir())}

    with tempfile.TemporaryDirectory() as tmp:
        home = Path(tmp)
        alpha_dir = home / "alpha"
        alpha_args = [
            "--name", "alpha", "--port", "8000",
            "--domain", "alpha.example.com", "--root", "/opt/alpha",
            "--ssh-user", "deploy", "--ssh-addr", "192.0.2.10",
            "--regex-route", "^/p/[a-z]{2,8}$=p.html",
            "--page-route", "/dash=dash.html",
        ]

        # 1: a clean run writes the trio and exits 0.
        code = run_cli(alpha_args + ["--out-dir", str(alpha_dir)])
        if code != 0:
            return failures + [f"clean run exited {code}, want 0"]
        first = read(alpha_dir)
        if set(first) != {"alpha.service", "nginx.conf", "deploy.sh"}:
            failures.append(f"clean run wrote {sorted(first)}")

        # 2: same flags, same bytes. A scaffold that is not reproducible cannot
        # be diffed against the unit already installed on the host.
        twin = home / "alpha-twin"
        if run_cli(alpha_args + ["--out-dir", str(twin)]) != 0:
            failures.append("second identical run did not exit 0")
        elif read(twin) != first:
            failures.append("identical flags produced different bytes")

        # 3: a rerun over existing files is refused, and refuses without
        # touching them — the unit on disk may already be hand-edited.
        (alpha_dir / "alpha.service").write_text("EDITED\n", encoding="utf-8")
        if run_cli(alpha_args + ["--out-dir", str(alpha_dir)]) != 1:
            failures.append("overwriting without --force did not exit 1")
        if (alpha_dir / "alpha.service").read_text(encoding="utf-8") != "EDITED\n":
            failures.append("a refused run still rewrote the unit")

        # 4: --force is the only way through, and restores the same bytes.
        if run_cli(alpha_args + ["--out-dir", str(alpha_dir), "--force"]) != 0:
            failures.append("--force did not exit 0")
        elif read(alpha_dir) != first:
            failures.append("--force wrote different bytes")

        nginx = first["nginx.conf"]
        service = first["alpha.service"]
        deploy = first["deploy.sh"]

        # 5: the trap this tool exists to encode. An unquoted regex containing
        # '{' makes nginx read a block open and `nginx -t` fails outright.
        if 'location ~ "^/p/[a-z]{2,8}$"' not in nginx:
            failures.append("the regex location is not emitted quoted")
        if re.search(r"location\s+~\s+[^\"]", nginx):
            failures.append("an unquoted regex location was emitted")

        # 6: an exact page route stays an exact match, not a prefix.
        if "location = /dash { try_files /dash.html =404; }" not in nginx:
            failures.append("the page route is not an exact location")

        # 7: the rsync flag that wipes the host's .env and .venv. Read the
        # runnable lines only — the template carries a comment naming the flag
        # precisely so a reader does not reintroduce it.
        runnable = "\n".join(line for line in deploy.splitlines()
                             if not line.lstrip().startswith("#"))
        if "--delete-excluded" in runnable:
            failures.append("deploy.sh uses --delete-excluded, which wipes "
                            "excluded paths on the host")
        if "--delete " not in runnable:
            failures.append("deploy.sh does not prune with --delete")

        # 8: the generated script has to be runnable.
        if (alpha_dir / "deploy.sh").stat().st_mode & 0o777 != 0o755:
            failures.append("deploy.sh is not mode 755")

        # 9: every collidable identity is namespaced by --name. Scaffold a
        # sibling and prove no token of one leaks into the other.
        beta_dir = home / "beta"
        beta_args = ["--name", "beta", "--port", "8001",
                     "--domain", "beta.example.com", "--root", "/opt/beta",
                     "--ssh-user", "deploy", "--ssh-addr", "192.0.2.10",
                     "--out-dir", str(beta_dir)]
        if run_cli(beta_args) != 0:
            failures.append("the sibling scaffold did not exit 0")
        else:
            beta = read(beta_dir)
            if "beta.service" not in beta:
                failures.append("the sibling unit is not named after --name")
            for marker in ("User=alpha", "Group=alpha", "ReadWritePaths=/var/lib/alpha",
                           "alpha.wsgi:application"):
                if marker not in service:
                    failures.append(f"{marker!r} missing from the unit")
                if marker.replace("alpha", "beta") not in beta["beta.service"]:
                    failures.append(f"the sibling unit does not namespace {marker!r}")
            if "zone=alphaapi" not in nginx or "zone=betaapi" not in beta["nginx.conf"]:
                failures.append("the limit_req zone is not namespaced by --name")
            for label, blob in (("unit", beta["beta.service"]),
                                ("vhost", beta["nginx.conf"]),
                                ("deploy.sh", beta["deploy.sh"])):
                if "alpha" in blob:
                    failures.append(f"the sibling {label} carries the other "
                                    "app's identity")

        # 10: an explicit override replaces the derived identity everywhere.
        over_dir = home / "over"
        if run_cli(["--name", "gamma", "--port", "9000",
                    "--domain", "gamma.example.com", "--root", "/opt/gamma",
                    "--ssh-user", "deploy", "--ssh-addr", "192.0.2.10",
                    "--user", "www-run", "--group", "www-grp",
                    "--state-dir", "/srv/state/gamma", "--zone", "gzone",
                    "--webroot", "/srv/www/gamma",
                    "--out-dir", str(over_dir)]) != 0:
            failures.append("the override run did not exit 0")
        else:
            over = read(over_dir)
            for marker, where in (("User=www-run", "gamma.service"),
                                  ("Group=www-grp", "gamma.service"),
                                  ("ReadWritePaths=/srv/state/gamma", "gamma.service"),
                                  ("zone=gzone", "nginx.conf"),
                                  ("root /srv/www/gamma;", "nginx.conf")):
                if marker not in over[where]:
                    failures.append(f"override {marker!r} not honoured in {where}")

        # 11-14: input the tool must refuse rather than scaffold.
        bad = home / "bad"
        rejects = [
            (["--name", "Alpha"], "an uppercase --name"),
            (["--name", "alpha", "--port", "80"], "a privileged --port"),
            (["--name", "alpha", "--domain", "alpha_example.com"], "an invalid --domain"),
            (["--name", "alpha", "--page-route", "/dash"], "a route with no '='"),
        ]
        for extra, label in rejects:
            argv = ["--name", "alpha", "--port", "8000",
                    "--domain", "alpha.example.com", "--root", "/opt/alpha",
                    "--ssh-user", "deploy", "--ssh-addr", "192.0.2.10",
                    "--out-dir", str(bad)] + extra
            code = run_cli(argv)
            if code != 2:
                failures.append(f"{label}: exit {code}, want 2")

        # 15: a missing required flag is refused, not defaulted. --ssh-addr in
        # particular has no default because a wrong one deploys to a stranger.
        if run_cli(["--name", "alpha", "--port", "8000",
                    "--domain", "alpha.example.com", "--root", "/opt/alpha",
                    "--out-dir", str(bad)]) != 2:
            failures.append("a missing --ssh-user/--ssh-addr did not exit 2")

        # 16: --check-local refuses an identity already present. The state dir
        # is pointed at the fixture tree, so this reads nothing outside it that
        # it does not already read on every run.
        taken = home / "taken"
        taken.mkdir()
        code = run_cli(["--name", "alpha", "--port", "8000",
                        "--domain", "alpha.example.com", "--root", "/opt/alpha",
                        "--ssh-user", "deploy", "--ssh-addr", "192.0.2.10",
                        "--state-dir", str(taken), "--check-local",
                        "--out-dir", str(home / "unused")])
        if code != 3:
            failures.append(f"--check-local over a taken state dir: exit {code}, want 3")
        if (home / "unused").exists():
            failures.append("--check-local wrote output before refusing")
    return failures


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", help="service identity, [a-z][a-z0-9-]+")
    ap.add_argument("--port", type=int, help="gunicorn loopback port")
    ap.add_argument("--domain", help="public hostname")
    ap.add_argument("--root", help="app dir on the host, e.g. /opt/<name>")
    ap.add_argument("--out-dir", default="deploy", help="where to write the trio (default deploy/)")
    ap.add_argument("--wsgi", help="wsgi target (default <name>.wsgi:application)")
    ap.add_argument("--user", help="unix user (default <name>)")
    ap.add_argument("--group", help="unix group (default = user)")
    ap.add_argument("--state-dir", help="writable state dir (default /var/lib/<name>)")
    ap.add_argument("--webroot", help="static root (default /var/www/<domain>)")
    ap.add_argument("--zone", help="nginx limit_req zone (default <name>api)")
    ap.add_argument("--backend", default="backend", help="backend subdir (default backend)")
    ap.add_argument("--frontend", default="frontend", help="frontend subdir (default frontend)")
    ap.add_argument("--test-labels", default="", help="labels for the deploy test gate")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--rate", default="10r/s")
    ap.add_argument("--burst", type=int, default=20)
    ap.add_argument("--ssh-user", help="deploy user on the target host")
    ap.add_argument("--ssh-addr",
                    help="target host address; no default — a wrong one deploys to a stranger")
    ap.add_argument("--ssh-port", type=int, default=22)
    ap.add_argument("--ssh-key", default="~/.ssh/id_ed25519",
                    help="private key for the deploy user; SSH_KEY env overrides at run time")
    ap.add_argument("--page-route", action="append", default=[], metavar="PATH=FILE",
                    help="exact location, e.g. /dashboard=dashboard.html (repeatable)")
    ap.add_argument("--regex-route", action="append", default=[], metavar="REGEX=FILE",
                    help="regex location, always emitted quoted (repeatable)")
    ap.add_argument("--check-local", action="store_true",
                    help="fail with exit 3 if this identity already exists on this machine")
    ap.add_argument("--force", action="store_true", help="overwrite existing output files")
    ap.add_argument("--self-test", action="store_true",
                    help="run the built-in fixtures and exit")
    args = ap.parse_args()

    if args.self_test:
        failures = self_test()
        for failure in failures:
            print(f"{NAME}: self-test: {failure}", file=sys.stderr)
        print(f"{NAME}: self-test checks=16 failures={len(failures)}")
        return 1 if failures else 0

    # The six identities with no safe default. Checked here rather than by
    # argparse's required=True so --self-test needs no other flag.
    missing = [flag for flag, value in (
        ("--name", args.name), ("--port", args.port), ("--domain", args.domain),
        ("--root", args.root), ("--ssh-user", args.ssh_user),
        ("--ssh-addr", args.ssh_addr)) if value is None]
    if missing:
        print(f"{NAME}: the following arguments are required: "
              f"{', '.join(missing)}", file=sys.stderr)
        return 2

    if not NAME_RE.match(args.name):
        print(f"deploy-scaffold: --name must match {NAME_RE.pattern}", file=sys.stderr)
        return 2
    if not DOMAIN_RE.match(args.domain):
        print("deploy-scaffold: --domain must be a bare hostname", file=sys.stderr)
        return 2
    if not 1024 <= args.port <= 65535:
        print("deploy-scaffold: --port must be 1024-65535", file=sys.stderr)
        return 2

    name = args.name
    user = args.user or name
    group = args.group or user
    state_dir = args.state_dir or f"/var/lib/{name}"
    webroot = args.webroot or f"/var/www/{args.domain}"
    zone = args.zone or f"{name}api"
    wsgi = args.wsgi or f"{name}.wsgi:application"

    if args.check_local:
        taken = []
        if Path(f"/etc/systemd/system/{name}.service").exists():
            taken.append(f"/etc/systemd/system/{name}.service")
        if Path(state_dir).exists():
            taken.append(state_dir)
        if Path(f"/etc/nginx/sites-available/{args.domain}").exists():
            taken.append(f"/etc/nginx/sites-available/{args.domain}")
        if taken:
            print("deploy-scaffold: identity already taken: " + ", ".join(taken),
                  file=sys.stderr)
            return 3

    try:
        pages = [parse_route(s, "page") for s in args.page_route]
        regexes = [parse_route(s, "regex") for s in args.regex_route]
    except ValueError as exc:
        print(f"deploy-scaffold: {exc}", file=sys.stderr)
        return 2

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    targets = {
        out / f"{name}.service": SERVICE_TMPL.format(
            name=name, domain=args.domain, user=user, group=group, root=args.root,
            backend=args.backend, wsgi=wsgi, port=args.port, workers=args.workers,
            state_dir=state_dir),
        out / "deploy.sh": DEPLOY_TMPL.format(
            name=name, domain=args.domain, user=user, group=group, root=args.root,
            backend=args.backend, frontend=args.frontend, webroot=webroot,
            state_dir=state_dir, test_labels=args.test_labels,
            ssh_user=args.ssh_user, ssh_addr=args.ssh_addr,
            ssh_port=args.ssh_port, ssh_key=args.ssh_key),
    }

    body = NGINX_HEAD.format(name=name, domain=args.domain, zone=zone, rate=args.rate,
                             burst=args.burst, port=args.port, webroot=webroot)
    if regexes:
        body += ("\n  # A regex containing {n} MUST be quoted — unquoted, nginx parses\n"
                 "  # '{' as a block open and the whole config fails nginx -t.\n")
        for pattern, target in regexes:
            body += f'  location ~ "{pattern}" {{ try_files /{target} =404; }}\n'
    if pages:
        body += "\n"
        for pattern, target in pages:
            body += f"  location = {pattern} {{ try_files /{target} =404; }}\n"
    body += "\n" + NGINX_TAIL.format(domain=args.domain)
    targets[out / "nginx.conf"] = body

    existing = [p.name for p in targets if p.exists()]
    if existing and not args.force:
        print(f"deploy-scaffold: refusing to overwrite {', '.join(sorted(existing))} "
              f"in {out} (use --force)", file=sys.stderr)
        return 1

    for path, text in targets.items():
        path.write_text(text, encoding="utf-8")
    (out / "deploy.sh").chmod(0o755)

    print(f"deploy-scaffold: name={name} service={name}.service user={user}:{group} "
          f"port={args.port} zone={zone} state={state_dir} webroot={webroot} "
          f"-> {out}/{{{name}.service,nginx.conf,deploy.sh}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
