#!/usr/bin/env bash
# plan-scaffold.sh — Scaffold a 30-60-90 day plan from a role slug and JD file.
#
# Usage: ./plan-scaffold.sh <role-slug> <jd-file> > plan.md
#
# Arguments:
#   role-slug   Short role identifier (e.g. "engineer", "sales-rep", "pm")
#   jd-file     Path to the job description markdown file
#
# Output: A markdown 30-60-90 plan skeleton to stdout.
# Notes:
#   - All milestones marked (M) are manager-set and must be reviewed before sharing with hire.
#   - Milestones not derivable from the JD are marked (synthetic — confirm with manager).
#   - Co-author with the hire on Day 1; this is a draft, not a final document.

set -euo pipefail

ROLE="${1:-role}"
JD_FILE="${2:-jd.md}"

if [[ ! -f "$JD_FILE" ]]; then
  echo "Error: JD file '$JD_FILE' not found." >&2
  exit 1
fi

JD_BASENAME="$(basename "$JD_FILE")"

cat <<MD
# 30-60-90 Day Plan — ${ROLE}

> Source JD: ${JD_BASENAME}
> Status: DRAFT — co-author with hire on Day 1 before finalizing.
> Legend: (M) = manager-set milestone | (synthetic — confirm) = not grounded in JD

---

## Days 1-30 — Learn

**Objective:** Build context, relationships, and understanding of the team's goals and ways of working.
**Gate:** Observable artifact at day 30 — written 1-pager observations shared with manager.

### Milestones

- [ ] Environment fully set up and verified (day 1) (M)
- [ ] Met all immediate team members (week 1) (M)
- [ ] Completed all required access provisioning and compliance training (week 2) (M)
- [ ] Shadowed at least 3 cross-functional partners (week 2-3) (synthetic — confirm)
- [ ] Read top-5 docs flagged by manager (week 2-3) (M)
- [ ] Day-30 check-in: written 1-pager observations — opportunities, risks, questions (day 25-30) (M)

### Day-30 Success Criteria

- [ ] Can describe team's current quarter goals and this role's contribution.
- [ ] Knows who to contact for decisions outside immediate team.
- [ ] Has documented goals for days 31-60, agreed with manager.

---

## Days 31-60 — Contribute

**Objective:** Apply knowledge, own a first project end-to-end, demonstrate core competencies.
**Gate:** Observable artifact — completed project with deliverable the team can reference.

### Milestones

- [ ] [First project — define scope with manager at day-30 review] (M)
- [ ] Active contributor in at least 2 recurring ceremonies per week (synthetic — confirm)
- [ ] Built working relationships with 3-5 cross-functional stakeholders (synthetic — confirm)
- [ ] Received and acted on feedback from manager and one peer (M)
- [ ] Day-60 review: deliver project, document goals for days 61-90 (M)

### Day-60 Success Criteria

- [ ] First project completed (artifact exists).
- [ ] Works with minimal supervision on familiar tasks.
- [ ] Has proposed at least one process or practice improvement.

---

## Days 61-90 — Execute

**Objective:** Work independently, deliver measurable results, contribute to team planning.
**Gate:** Formal 90-day review against documented success criteria.

### Milestones

- [ ] [Major project or milestone — define at day-60 review] (M)
- [ ] Handles most responsibilities without requiring guidance (M)
- [ ] Proactively identified at least one opportunity or risk (synthetic — confirm)
- [ ] Development plan for next quarter documented (M)
- [ ] Day-90 formal performance review (M)

### Day-90 Success Criteria

- [ ] Meets or exceeds performance expectations.
- [ ] Works autonomously 80%+ of the time.
- [ ] Development plan for Q+1 agreed with manager.

---

## Check-In Schedule

| Day | Type | Owner | Focus |
|-----|------|-------|-------|
| 7 | Informal pulse | Manager | Early friction, blockers |
| 25-30 | 30-day review | Manager | Gate to Contribute phase |
| 45 | Skip-level | Manager's manager | Independent calibration |
| 60 | 60-day review | Manager | Gate to Execute phase |
| 90 | Formal review | Manager | Transition to standard performance cycle |

---

*Generated by plan-scaffold.sh — review and personalize before sharing with the hire.*
MD
