[install]
frozen-lockfile = true
registry = "https://registry.npmjs.org/"

[test]
coverage = true
coverageDir = "./coverage"
timeout = 5000

[build]
minify = true
sourcemap = "external"
target = "bun"
outdir = "./dist"
