# minimum viable filled-in example of gcp-compute-gke.yaml
name: example-name
mode: example-mode
region: example-region
node_pools:
  - example-node_pools-1
workload_identity: true
private_nodes: true
