#!/usr/bin/env python3
"""validate-trade-off-build-vs-buy.py

Validate a Build vs Buy ADR artefact against the JSON Schema declared in
`content/02-output-contract.xml`. Stdlib-only; no external pip deps.

The schema is inlined below rather than imported: `faion get-content`
materialises only this one methodology's `scripts/` on the user's machine, so
a shared helper module would never arrive with it.

Enforced: required · type · enum · pattern · format · minLength / maxLength ·
minItems / maxItems · minimum / maximum · additionalProperties, plus the house
rules a schema cannot state (a required field left empty or still reading TBD /
TODO / FIXME, and `owner` naming a group rather than a person).

Inputs:
    --file PATH       path to artefact JSON
    --self-test       run built-in fixtures
    --help            this message

Exit codes:
    0 = valid
    1 = invalid (violations printed to stderr)
    2 = usage / unreadable / parse error

Generated by scripts/regen-methodology-validators.py from the contract above.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# --- the output contract, inlined ------------------------------------------
SCHEMA = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://faion.net/schemas/trade-off-build-vs-buy.json",
  "type": "object",
  "title": "Build vs Buy ADR",
  "required": [
    "adr_id",
    "status",
    "decision",
    "differentiation_score",
    "tco_3y",
    "exit_plan",
    "pilot_pass",
    "rejected",
    "review_trigger",
    "version",
    "last_reviewed"
  ],
  "additionalProperties": False,
  "properties": {
    "adr_id": {
      "type": "string",
      "pattern": "^adr-bb-[a-z0-9-]+$"
    },
    "status": {
      "enum": [
        "proposed",
        "accepted",
        "superseded",
        "deprecated"
      ]
    },
    "decision": {
      "enum": [
        "build",
        "buy",
        "hybrid",
        "adopt_oss"
      ]
    },
    "differentiation_score": {
      "type": "integer",
      "minimum": 1,
      "maximum": 5
    },
    "tco_3y": {
      "type": "object",
      "required": [
        "build_usd",
        "buy_usd",
        "hybrid_usd"
      ],
      "properties": {
        "build_usd": {
          "type": "number",
          "minimum": 0
        },
        "buy_usd": {
          "type": "number",
          "minimum": 0
        },
        "hybrid_usd": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "exit_plan": {
      "type": [
        "string",
        "null"
      ]
    },
    "pilot_pass": {
      "type": "boolean"
    },
    "rejected": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "option",
          "reason"
        ],
        "properties": {
          "option": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          }
        }
      }
    },
    "review_trigger": {
      "type": "string",
      "minLength": 10
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "last_reviewed": {
      "type": "string",
      "format": "date"
    }
  }
}

REQUIRED = [
  "adr_id",
  "decision",
  "differentiation_score",
  "exit_plan",
  "last_reviewed",
  "pilot_pass",
  "rejected",
  "review_trigger",
  "status",
  "tco_3y",
  "version"
]


# Both sets are the UNION of every generic-owner and placeholder vocabulary
# already in use across the corpus's hand-written validators, so a regenerated
# file can never accept an owner or a token one of them rejected.
FORBIDDEN_OWNERS = {
    "", "?", "all", "anyone", "backlog", "client", "client team", "data team",
    "design", "design team", "design-team", "engineering", "everyone",
    "features", "n/a", "na", "none", "ops", "ops team", "ourselves", "somebody",
    "someone", "squad", "tbd", "team", "the client", "the group", "the squad",
    "the team", "they", "todo", "unassigned", "us", "we",
}
PLACEHOLDERS = {
    "...", "<fill>", "???", "as shown", "changeme", "fill_me", "fixme", "n/a",
    "na", "none", "null", "placeholder", "see image", "tbd", "todo", "wip",
    "xxx",
}

_FORMATS = {
    "date-time": re.compile(
        r"^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?"
        r"(?:Z|[+-]\d{2}:?\d{2})?$"
    ),
    "date": re.compile(r"^\d{4}-\d{2}-\d{2}$"),
    "email": re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$"),
    "uri": re.compile(r"^[a-zA-Z][a-zA-Z0-9+.\-]*:\S*$"),
    "uri-reference": re.compile(r"^\S+$"),
}

_PY_TYPES = {"object": dict, "array": list, "string": str, "null": type(None)}


def _type_ok(value, declared) -> bool:
    names = declared if isinstance(declared, list) else [declared]
    for name in names:
        if name == "integer":
            ok = isinstance(value, int) and not isinstance(value, bool)
        elif name == "number":
            ok = isinstance(value, (int, float)) and not isinstance(value, bool)
        elif name == "boolean":
            ok = isinstance(value, bool)
        elif name in _PY_TYPES:
            ok = isinstance(value, _PY_TYPES[name])
        else:
            ok = True
        if ok:
            return True
    return False


def _label(path: str) -> str:
    return path or "<root>"


def _check(value, schema: dict, path: str, errs: list) -> None:
    """Walk one schema node against one value, appending findings."""
    declared = schema.get("type")
    if declared is not None and not _type_ok(value, declared):
        errs.append(
            f"{_label(path)}: expected type {declared}, "
            f"got {type(value).__name__}"
        )
        return

    enum = schema.get("enum")
    if enum is not None and value not in enum:
        errs.append(f"{_label(path)}: {value!r} not in allowed enum {enum!r}")

    if "const" in schema and value != schema["const"]:
        errs.append(
            f"{_label(path)}: {value!r} is not the required "
            f"const {schema['const']!r}"
        )

    if isinstance(value, str):
        pattern = schema.get("pattern")
        if pattern and not re.search(pattern, value):
            errs.append(
                f"{_label(path)}: {value!r} does not match pattern {pattern!r}"
            )
        fmt = schema.get("format")
        rx = _FORMATS.get(fmt) if isinstance(fmt, str) else None
        if rx is not None and not rx.match(value):
            errs.append(f"{_label(path)}: {value!r} is not a valid {fmt}")
        low = schema.get("minLength")
        if isinstance(low, int) and len(value) < low:
            errs.append(
                f"{_label(path)}: length {len(value)} is under minLength {low}"
            )
        high = schema.get("maxLength")
        if isinstance(high, int) and len(value) > high:
            errs.append(
                f"{_label(path)}: length {len(value)} is over maxLength {high}"
            )

    if isinstance(value, list):
        low = schema.get("minItems")
        if isinstance(low, int) and len(value) < low:
            errs.append(
                f"{_label(path)}: {len(value)} items is under minItems {low}"
            )
        high = schema.get("maxItems")
        if isinstance(high, int) and len(value) > high:
            errs.append(
                f"{_label(path)}: {len(value)} items is over maxItems {high}"
            )
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for i, element in enumerate(value):
                _check(element, item_schema, f"{_label(path)}[{i}]", errs)

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        low = schema.get("minimum")
        if isinstance(low, (int, float)) and value < low:
            errs.append(f"{_label(path)}: {value} is below minimum {low}")
        high = schema.get("maximum")
        if isinstance(high, (int, float)) and value > high:
            errs.append(f"{_label(path)}: {value} is above maximum {high}")
        xlow = schema.get("exclusiveMinimum")
        if isinstance(xlow, (int, float)) and value <= xlow:
            errs.append(
                f"{_label(path)}: {value} is not above exclusiveMinimum {xlow}"
            )
        xhigh = schema.get("exclusiveMaximum")
        if isinstance(xhigh, (int, float)) and value >= xhigh:
            errs.append(
                f"{_label(path)}: {value} is not below exclusiveMaximum {xhigh}"
            )

    if isinstance(value, dict):
        props = schema.get("properties") or {}
        required = schema.get("required") or []
        for key in required:
            if key not in value:
                errs.append(
                    f"{_label(path)}: missing required field: {key}"
                )
        if schema.get("additionalProperties") is False:
            for key in value:
                if key not in props:
                    errs.append(
                        f"{_label(path)}: unknown field {key!r} "
                        f"(additionalProperties: false)"
                    )
        for key, sub in props.items():
            if key in value and isinstance(sub, dict):
                _check(value[key], sub, f"{path}.{key}" if path else key, errs)
        _placeholders(value, required, path, errs)


def _placeholders(obj: dict, required, path: str, errs: list) -> None:
    """House rules the schema cannot express: a required field that is
    present but empty or still carrying a placeholder token, and an `owner`
    naming a group rather than a person."""
    for key in required:
        if key not in obj:
            continue
        where = f"{path}.{key}" if path else key
        value = obj[key]
        if isinstance(value, str):
            if not value.strip():
                errs.append(f"{where}: required field is empty")
            elif value.strip().lower() in PLACEHOLDERS:
                errs.append(f"{where}: required field is a placeholder: {value!r}")
        elif isinstance(value, (list, dict)) and not value:
            errs.append(f"{where}: required field is empty")
    owner = obj.get("owner")
    if isinstance(owner, str) and owner.strip().lower() in FORBIDDEN_OWNERS:
        errs.append(
            f"{(path + '.owner') if path else 'owner'}: "
            f"owner is a generic group: {owner!r}"
        )


def validate(obj) -> list:
    """Pure: artefact in, list of finding strings out. Empty list means valid."""
    if not isinstance(obj, dict):
        return ["<root>: must be a JSON object"]
    errs: list = []
    _check(obj, SCHEMA, "", errs)
    return errs


# --- fixtures --------------------------------------------------------------
# OK: contract example.
OK = {
       "adr_id": "adr-bb-helpdesk-2026-05",
       "status": "accepted",
       "decision": "buy",
       "differentiation_score": 2,
       "tco_3y": {
         "build_usd": 420000,
         "buy_usd": 180000,
         "hybrid_usd": 240000
       },
       "exit_plan": "Weekly CSV export + 90-day termination clause + Freshdesk as alternative provider.",
       "pilot_pass": True,
       "rejected": [
         {
           "option": "build",
           "reason": "Differentiation score 2; 3-year TCO 2.3x Buy."
         },
         {
           "option": "adopt_oss",
           "reason": "OSS osTicket maintenance burden > Buy cost saving."
         }
       ],
       "review_trigger": "Zendesk price increase > 30% YoY OR support volume > 5x current OR feature gap blocks growth.",
       "version": "1.0.0",
       "last_reviewed": "2026-05-23"
     }

# BAD: OK with exactly one declared constraint violated — status outside its enum.
BAD = {
        "adr_id": "adr-bb-helpdesk-2026-05",
        "status": "__not_in_enum__",
        "decision": "buy",
        "differentiation_score": 2,
        "tco_3y": {
          "build_usd": 420000,
          "buy_usd": 180000,
          "hybrid_usd": 240000
        },
        "exit_plan": "Weekly CSV export + 90-day termination clause + Freshdesk as alternative provider.",
        "pilot_pass": True,
        "rejected": [
          {
            "option": "build",
            "reason": "Differentiation score 2; 3-year TCO 2.3x Buy."
          },
          {
            "option": "adopt_oss",
            "reason": "OSS osTicket maintenance burden > Buy cost saving."
          }
        ],
        "review_trigger": "Zendesk price increase > 30% YoY OR support volume > 5x current OR feature gap blocks growth.",
        "version": "1.0.0",
        "last_reviewed": "2026-05-23"
      }

BAD_VIOLATES = 'status outside its enum'
BAD_EXPECT = 'not in allowed enum'


def self_test() -> int:
    """OK must pass. BAD is the contract's own valid example with exactly one
    declared constraint violated, and must be rejected *for that reason* —
    a fixture that only trips the presence checks would prove nothing."""
    errs_ok = validate(OK)
    if errs_ok:
        sys.stderr.write(f"self-test FAIL: valid fixture rejected: {errs_ok!r}\n")
        return 1
    errs_bad = validate(BAD)
    if not errs_bad:
        sys.stderr.write("self-test FAIL: invalid fixture accepted\n")
        return 1
    if not any(BAD_EXPECT in e for e in errs_bad):
        sys.stderr.write(
            f"self-test FAIL: invalid fixture rejected for the wrong reason; "
            f"expected {BAD_EXPECT!r}, got {errs_bad!r}\n"
        )
        return 1
    sys.stdout.write(f"self-test OK ({BAD_VIOLATES})\n")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Both spellings are accepted. Most of the corpus passes `--file PATH`,
    # a minority passes a bare path; a regenerated validator must not break
    # whichever one a caller's scripts already use.
    ap.add_argument("artefact", nargs="?", help="path to artefact JSON")
    ap.add_argument("--file", type=str, help="path to artefact JSON")
    ap.add_argument("--self-test", action="store_true",
                    help="run built-in fixtures")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    target = args.file or args.artefact
    if not target:
        ap.print_help()
        return 2
    p = Path(target)
    if not p.is_file():
        sys.stderr.write(f"not a file: {p}\n")
        return 2
    try:
        obj = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.stderr.write(f"JSON parse error: {e}\n")
        return 2
    errs = validate(obj)
    if errs:
        for e in errs:
            sys.stderr.write(f"VIOLATION: {e}\n")
        return 1
    sys.stdout.write("OK\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
