#!/usr/bin/env bash
# ci-race.sh — CI script enforcing race detector, staticcheck, and goleak.
# Run on every PR for packages with goroutines.
set -euo pipefail
go vet ./...
go test -race -count=3 -timeout=120s ./...
go run honnef.co/go/tools/cmd/staticcheck@latest ./...
