// sd.config.js — Style Dictionary: W3C DTCG token JSON → Tailwind config + CSS variables
// Run: node sd.config.js
// Input:  tokens/**/*.json (W3C DTCG format)
// Output: src/styles/tokens.css + src/tw-tokens.js

const StyleDictionary = require('style-dictionary');

StyleDictionary.registerTransform({
  name: 'css/var-name',
  type: 'name',
  transformer: (token) =>
    `--${token.path.join('-').toLowerCase().replace(/\s+/g, '-')}`,
});

StyleDictionary.registerFormat({
  name: 'tailwind/tokens',
  formatter: ({ dictionary }) => {
    const colors  = {};
    const spacing = {};

    dictionary.allTokens.forEach((token) => {
      const varRef = `var(--${token.name})`;
      if (token.path[0] === 'color') {
        // Nested structure: color.primary.default → colors.primary.DEFAULT
        let obj = colors;
        token.path.slice(1, -1).forEach((seg) => {
          obj[seg] = obj[seg] || {};
          obj = obj[seg];
        });
        const last = token.path[token.path.length - 1];
        obj[last === 'default' ? 'DEFAULT' : last] = varRef;
      } else if (token.path[0] === 'spacing') {
        const key = token.path.slice(1).join('-');
        spacing[key] = varRef;
      }
    });

    return `// Auto-generated by sd.config.js — do not edit manually
module.exports = ${JSON.stringify({ colors, spacing }, null, 2)};
`;
  },
});

module.exports = {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transforms: ['attribute/cti', 'css/var-name', 'color/hsl'],
      buildPath: 'src/styles/',
      files: [{ destination: 'tokens.css', format: 'css/variables' }],
    },
    tailwind: {
      transforms: ['attribute/cti', 'css/var-name'],
      buildPath: 'src/',
      files: [{ destination: 'tw-tokens.js', format: 'tailwind/tokens' }],
    },
  },
};
