#!/usr/bin/env python3
"""regen-methodology-validators.py — rebuild per-methodology output validators
from the JSON Schema their own output contract already declares.

The problem. Every methodology carries `content/02-output-contract.xml` with a
real draft-07 schema inside it, and a `scripts/validate-<slug>.py` that is
supposed to enforce that schema. A large share of those validators check only
that the required keys are present and are not the literal "TBD", while the
contract beside them declares `enum`, `pattern`, `minItems`, `minLength`,
`minimum` and `maximum` that nothing ever reads. Recovering those is
mechanical: the constraints are already written down.

What this does. For each methodology in scope it extracts the schema from the
contract XML and emits a **self-contained** `validate-<slug>.py` that enforces
required / type / enum / pattern / format / minLength / maxLength / minItems /
maxItems / minimum / maximum / additionalProperties, plus the house placeholder
rules (a required field left empty or set to TBD / TODO / FIXME; `owner` set to
a generic group term).

Self-contained is a hard constraint, not a style choice. `faion get-content`
materialises exactly one methodology's `scripts/` into `~/.faion/<slug>/scripts/`
on the end user's machine. A shared helper module would never be shipped
alongside it, so every constraint is inlined into every file. Do not refactor
these toward a common import.

The BAD fixture is derived from the contract by mutating the valid example so
it violates exactly one *declared* constraint, and the generated `--self-test`
asserts the resulting finding names that constraint. A `BAD = {}` fixture only
ever proves the presence checks fire; this proves the file implements the
contract it was generated from.

Safety. The generator can only strengthen. Before replacing a file it measures
the constraints the existing validator enforces, two independent ways:

  1. behavioural — probe the old validator (as a subprocess, its real
     user-visible contract) with the valid fixture and with every mutation the
     NEW validator would accept. If the old one accepts the valid fixture but
     rejects a mutation the new one waves through, the new one is weaker.
  2. static — an AST census of the old source mapped onto the same constraint
     categories the schema declares. If the old file scores higher in any
     single category, the new one is weaker.

A third outcome refuses too: if the old validator will not accept the
contract's own valid example, probe 1 is inconclusive — it rejects every
mutation for an unrelated reason — and "cannot prove not-weaker" is treated as
weaker. Measured on infra/terraform-state, that case hid a cross-field rule no
JSON Schema can express. `--allow-static-only` overrides it deliberately.

Any of these verdicts refuses the slug and leaves the file untouched. Three index
builders were deleted from this repo for silently emptying the files they
targeted; a generator that cannot regress is the price of trusting this one.

Usage:
    regen-methodology-validators.py                     dry-run, whole corpus
    regen-methodology-validators.py --domain dev        dry-run, one domain
    regen-methodology-validators.py --slug a --slug b   dry-run, named slugs
    regen-methodology-validators.py --slug a --write    write those slugs
    regen-methodology-validators.py --self-test         the generator's own tests

Exit codes:
    0 = ran clean            1 = a slug was refused or errored
    2 = usage error
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

GENERATED_MARKER = "Generated by scripts/regen-methodology-validators.py"

REPO_ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = REPO_ROOT / "skills" / "faion" / "knowledge"

# Constraint categories. Both the schema census and the AST census of an
# existing validator are reported in these terms so the two are comparable.
# `length` and `items` are deliberately one bucket. Both sides express a size
# bound as `len(x) <op> n`, and nothing in the source says whether x is a
# string or a list — scoring one comparison in two bins made the old side
# look twice as strict as it was and refused slugs the generator improves.
CATEGORIES = (
    "required",
    "type",
    "enum",
    "pattern",
    "size",
    "numeric",
    "unknown",
    "placeholder",
)

# The raw schema keywords behind each category, for the per-slug report.
KEYWORDS_BY_CATEGORY = {
    "enum": ("enum", "const"),
    "pattern": ("pattern", "format"),
    "size": ("minLength", "maxLength", "minItems", "maxItems"),
    "numeric": ("minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"),
}


# --------------------------------------------------------------------------
# contract extraction
# --------------------------------------------------------------------------

_JSON_COMMENT = re.compile(r"^\s*//.*$", re.MULTILINE)
_TRAILING_COMMA = re.compile(r",(\s*[}\]])")


def _loads_lenient(text: str) -> Any:
    """Parse JSON, tolerating the // comments and trailing commas that a few
    hand-written contracts carry."""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    cleaned = _TRAILING_COMMA.sub(r"\1", _JSON_COMMENT.sub("", text))
    return json.loads(cleaned)


def _parent_map(tree: ET.ElementTree) -> dict[ET.Element, ET.Element]:
    return {child: parent for parent in tree.iter() for child in parent}


def _in_example(el: ET.Element, parents: dict[ET.Element, ET.Element]) -> str | None:
    """Return the `valid` attribute of the enclosing <example>, or None."""
    cur = el
    while cur in parents:
        cur = parents[cur]
        if cur.tag == "example":
            return (cur.get("valid") or "").strip().lower()
    return None


def _section_title(el: ET.Element, parents: dict[ET.Element, ET.Element]) -> str:
    cur = el
    while cur in parents:
        cur = parents[cur]
        if cur.tag == "section":
            return (cur.get("title") or "").lower()
    return ""


def _schema_score(obj: Any) -> int:
    """How much a parsed blob looks like the artefact schema rather than an
    example payload or some incidental JSON."""
    if not isinstance(obj, dict):
        return -1
    score = 0
    if "$schema" in obj:
        score += 4
    if obj.get("type") == "object":
        score += 2
    if isinstance(obj.get("properties"), dict):
        score += 3
    if isinstance(obj.get("required"), list):
        score += 2
    if "$id" in obj:
        score += 1
    return score


def read_contract(contract: Path) -> dict[str, Any]:
    """Extract {schema, example, notes} from a 02-output-contract.xml."""
    out: dict[str, Any] = {"schema": None, "example": None, "notes": []}
    try:
        tree = ET.parse(contract)
    except (ET.ParseError, OSError) as exc:
        out["notes"].append(f"contract unparseable: {exc}")
        return out
    parents = _parent_map(tree)

    best_schema, best_score = None, 0
    examples: list[Any] = []

    for el in tree.iter():
        if el.tag not in ("schema", "code"):
            continue
        lang = (el.get("lang") or "").lower()
        if el.tag == "code" and lang not in ("", "json"):
            continue
        raw = (el.text or "").strip()
        if not raw.startswith(("{", "[")):
            continue
        try:
            blob = _loads_lenient(raw)
        except (json.JSONDecodeError, ValueError):
            continue

        valid_attr = _in_example(el, parents)
        title = _section_title(el, parents)
        if valid_attr == "true" or "valid example" in title:
            if isinstance(blob, dict):
                examples.append(blob)
            continue
        if valid_attr in ("false",) or "invalid example" in title:
            continue

        score = _schema_score(blob)
        if el.tag == "schema":
            score += 3
        if "schema" in title:
            score += 2
        if score > best_score:
            best_schema, best_score = blob, score

    out["schema"] = best_schema
    if examples:
        out["example"] = examples[0]
    return out


def load_smoke_test(meth_dir: Path) -> Any:
    p = meth_dir / "templates" / "_smoke-test.json"
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


# --------------------------------------------------------------------------
# schema census — what the contract declares
# --------------------------------------------------------------------------

SUPPORTED = {
    "type", "enum", "pattern", "format", "minLength", "maxLength",
    "minItems", "maxItems", "minimum", "maximum", "exclusiveMinimum",
    "exclusiveMaximum", "required", "properties", "items",
    "additionalProperties",
}
IGNORED_NOISE = {"$schema", "$id", "title", "description", "default",
                 "examples", "$comment", "uniqueItems", "definitions"}


def walk_schema(schema: Any, path: str = ""):
    """Yield (path, node) for every schema node this generator understands."""
    if not isinstance(schema, dict):
        return
    yield path, schema
    for key, sub in (schema.get("properties") or {}).items():
        yield from walk_schema(sub, f"{path}.{key}" if path else key)
    items = schema.get("items")
    if isinstance(items, dict):
        yield from walk_schema(items, f"{path}[]")


def schema_census(schema: dict) -> dict[str, int]:
    cen = dict.fromkeys(CATEGORIES, 0)
    owner_seen = False
    for path, node in walk_schema(schema):
        cen["required"] += len(node.get("required") or [])
        if node.get("type"):
            cen["type"] += 1
        if node.get("enum") or "const" in node:
            cen["enum"] += 1
        if node.get("pattern"):
            cen["pattern"] += 1
        if node.get("format") in ("date-time", "date", "email", "uri", "uri-reference"):
            cen["pattern"] += 1
        cen["size"] += sum(
            1 for k in ("minLength", "maxLength", "minItems", "maxItems")
            if k in node
        )
        cen["numeric"] += sum(
            1 for k in ("minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum")
            if k in node
        )
        if node.get("additionalProperties") is False:
            cen["unknown"] += 1
        if path.split(".")[-1] == "owner":
            owner_seen = True
    # Placeholder rules are a fixed set — empty-required, TBD-token, generic
    # owner — not one per field. Counting them per field would show a bogus
    # "+9 placeholder" gain on a slug that gained nothing real.
    cen["placeholder"] = (2 if cen["required"] else 0) + (1 if owner_seen else 0)
    return cen


def declared_keywords(schema: dict) -> dict[str, int]:
    """Raw keyword counts, so a report can say `minItems x3` rather than only
    naming the category the keyword was binned into."""
    counts: dict[str, int] = {}
    every = [k for kws in KEYWORDS_BY_CATEGORY.values() for k in kws]
    for _, node in walk_schema(schema):
        for keyword in every:
            if keyword in node and node[keyword] not in (None, ""):
                counts[keyword] = counts.get(keyword, 0) + 1
        if node.get("additionalProperties") is False:
            counts["additionalProperties"] = counts.get("additionalProperties", 0) + 1
    return counts


def unsupported_keywords(schema: dict) -> set[str]:
    found: set[str] = set()
    stack = [schema]
    while stack:
        node = stack.pop()
        if isinstance(node, dict):
            for key, val in node.items():
                if key in ("properties", "definitions", "$defs"):
                    stack.extend(v for v in val.values() if isinstance(v, dict))
                    continue
                if key in ("oneOf", "anyOf", "allOf", "not", "$ref",
                           "patternProperties", "if", "then", "else"):
                    found.add(key)
                if key == "items" and isinstance(val, dict):
                    stack.append(val)
    return found


# --------------------------------------------------------------------------
# the checker algorithm — kept as source text so the generator and every
# generated file run byte-identical logic
# --------------------------------------------------------------------------

CHECKER_SOURCE = '''
# Both sets are the UNION of every generic-owner and placeholder vocabulary
# already in use across the corpus's hand-written validators, so a regenerated
# file can never accept an owner or a token one of them rejected.
FORBIDDEN_OWNERS = {
    "", "?", "all", "anyone", "backlog", "client", "client team", "data team",
    "design", "design team", "design-team", "engineering", "everyone",
    "features", "n/a", "na", "none", "ops", "ops team", "ourselves", "somebody",
    "someone", "squad", "tbd", "team", "the client", "the group", "the squad",
    "the team", "they", "todo", "unassigned", "us", "we",
}
PLACEHOLDERS = {
    "...", "<fill>", "???", "as shown", "changeme", "fill_me", "fixme", "n/a",
    "na", "none", "null", "placeholder", "see image", "tbd", "todo", "wip",
    "xxx",
}

_FORMATS = {
    "date-time": re.compile(
        r"^\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?"
        r"(?:Z|[+-]\\d{2}:?\\d{2})?$"
    ),
    "date": re.compile(r"^\\d{4}-\\d{2}-\\d{2}$"),
    "email": re.compile(r"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"),
    "uri": re.compile(r"^[a-zA-Z][a-zA-Z0-9+.\\-]*:\\S*$"),
    "uri-reference": re.compile(r"^\\S+$"),
}

_PY_TYPES = {"object": dict, "array": list, "string": str, "null": type(None)}


def _type_ok(value, declared) -> bool:
    names = declared if isinstance(declared, list) else [declared]
    for name in names:
        if name == "integer":
            ok = isinstance(value, int) and not isinstance(value, bool)
        elif name == "number":
            ok = isinstance(value, (int, float)) and not isinstance(value, bool)
        elif name == "boolean":
            ok = isinstance(value, bool)
        elif name in _PY_TYPES:
            ok = isinstance(value, _PY_TYPES[name])
        else:
            ok = True
        if ok:
            return True
    return False


def _label(path: str) -> str:
    return path or "<root>"


def _check(value, schema: dict, path: str, errs: list) -> None:
    """Walk one schema node against one value, appending findings."""
    declared = schema.get("type")
    if declared is not None and not _type_ok(value, declared):
        errs.append(
            f"{_label(path)}: expected type {declared}, "
            f"got {type(value).__name__}"
        )
        return

    enum = schema.get("enum")
    if enum is not None and value not in enum:
        errs.append(f"{_label(path)}: {value!r} not in allowed enum {enum!r}")

    if "const" in schema and value != schema["const"]:
        errs.append(
            f"{_label(path)}: {value!r} is not the required "
            f"const {schema['const']!r}"
        )

    if isinstance(value, str):
        pattern = schema.get("pattern")
        if pattern and not re.search(pattern, value):
            errs.append(
                f"{_label(path)}: {value!r} does not match pattern {pattern!r}"
            )
        fmt = schema.get("format")
        rx = _FORMATS.get(fmt) if isinstance(fmt, str) else None
        if rx is not None and not rx.match(value):
            errs.append(f"{_label(path)}: {value!r} is not a valid {fmt}")
        low = schema.get("minLength")
        if isinstance(low, int) and len(value) < low:
            errs.append(
                f"{_label(path)}: length {len(value)} is under minLength {low}"
            )
        high = schema.get("maxLength")
        if isinstance(high, int) and len(value) > high:
            errs.append(
                f"{_label(path)}: length {len(value)} is over maxLength {high}"
            )

    if isinstance(value, list):
        low = schema.get("minItems")
        if isinstance(low, int) and len(value) < low:
            errs.append(
                f"{_label(path)}: {len(value)} items is under minItems {low}"
            )
        high = schema.get("maxItems")
        if isinstance(high, int) and len(value) > high:
            errs.append(
                f"{_label(path)}: {len(value)} items is over maxItems {high}"
            )
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for i, element in enumerate(value):
                _check(element, item_schema, f"{_label(path)}[{i}]", errs)

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        low = schema.get("minimum")
        if isinstance(low, (int, float)) and value < low:
            errs.append(f"{_label(path)}: {value} is below minimum {low}")
        high = schema.get("maximum")
        if isinstance(high, (int, float)) and value > high:
            errs.append(f"{_label(path)}: {value} is above maximum {high}")
        xlow = schema.get("exclusiveMinimum")
        if isinstance(xlow, (int, float)) and value <= xlow:
            errs.append(
                f"{_label(path)}: {value} is not above exclusiveMinimum {xlow}"
            )
        xhigh = schema.get("exclusiveMaximum")
        if isinstance(xhigh, (int, float)) and value >= xhigh:
            errs.append(
                f"{_label(path)}: {value} is not below exclusiveMaximum {xhigh}"
            )

    if isinstance(value, dict):
        props = schema.get("properties") or {}
        required = schema.get("required") or []
        for key in required:
            if key not in value:
                errs.append(
                    f"{_label(path)}: missing required field: {key}"
                )
        if schema.get("additionalProperties") is False:
            for key in value:
                if key not in props:
                    errs.append(
                        f"{_label(path)}: unknown field {key!r} "
                        f"(additionalProperties: false)"
                    )
        for key, sub in props.items():
            if key in value and isinstance(sub, dict):
                _check(value[key], sub, f"{path}.{key}" if path else key, errs)
        _placeholders(value, required, path, errs)


def _placeholders(obj: dict, required, path: str, errs: list) -> None:
    """House rules the schema cannot express: a required field that is
    present but empty or still carrying a placeholder token, and an `owner`
    naming a group rather than a person."""
    for key in required:
        if key not in obj:
            continue
        where = f"{path}.{key}" if path else key
        value = obj[key]
        if isinstance(value, str):
            if not value.strip():
                errs.append(f"{where}: required field is empty")
            elif value.strip().lower() in PLACEHOLDERS:
                errs.append(f"{where}: required field is a placeholder: {value!r}")
        elif isinstance(value, (list, dict)) and not value:
            errs.append(f"{where}: required field is empty")
    owner = obj.get("owner")
    if isinstance(owner, str) and owner.strip().lower() in FORBIDDEN_OWNERS:
        errs.append(
            f"{(path + '.owner') if path else 'owner'}: "
            f"owner is a generic group: {owner!r}"
        )


def validate(obj) -> list:
    """Pure: artefact in, list of finding strings out. Empty list means valid."""
    if not isinstance(obj, dict):
        return ["<root>: must be a JSON object"]
    errs: list = []
    _check(obj, SCHEMA, "", errs)
    return errs
'''.strip("\n")


TAIL_SOURCE = '''
def self_test() -> int:
    """OK must pass. BAD is the contract's own valid example with exactly one
    declared constraint violated, and must be rejected *for that reason* —
    a fixture that only trips the presence checks would prove nothing."""
    errs_ok = validate(OK)
    if errs_ok:
        sys.stderr.write(f"self-test FAIL: valid fixture rejected: {errs_ok!r}\\n")
        return 1
    errs_bad = validate(BAD)
    if not errs_bad:
        sys.stderr.write("self-test FAIL: invalid fixture accepted\\n")
        return 1
    if not any(BAD_EXPECT in e for e in errs_bad):
        sys.stderr.write(
            f"self-test FAIL: invalid fixture rejected for the wrong reason; "
            f"expected {BAD_EXPECT!r}, got {errs_bad!r}\\n"
        )
        return 1
    sys.stdout.write(f"self-test OK ({BAD_VIOLATES})\\n")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Both spellings are accepted. Most of the corpus passes `--file PATH`,
    # a minority passes a bare path; a regenerated validator must not break
    # whichever one a caller's scripts already use.
    ap.add_argument("artefact", nargs="?", help="path to artefact JSON")
    ap.add_argument("--file", type=str, help="path to artefact JSON")
    ap.add_argument("--self-test", action="store_true",
                    help="run built-in fixtures")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    target = args.file or args.artefact
    if not target:
        ap.print_help()
        return 2
    p = Path(target)
    if not p.is_file():
        sys.stderr.write(f"not a file: {p}\\n")
        return 2
    try:
        obj = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.stderr.write(f"JSON parse error: {e}\\n")
        return 2
    errs = validate(obj)
    if errs:
        for e in errs:
            sys.stderr.write(f"VIOLATION: {e}\\n")
        return 1
    sys.stdout.write("OK\\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''.strip("\n")


# --------------------------------------------------------------------------
# fixture synthesis
# --------------------------------------------------------------------------

_PATTERN_CANDIDATES = [
    "1.0.0", "v1.0.0", "2026-01-01", "2026-01-01T00:00:00Z",
    "owner@example.com", "https://example.com/doc", "example",
    "example-value", "EXAMPLE", "ok", "draft", "abc", "a", "1", "0",
    "example_value", "example/value", "Example Value",
]


_CLASS_SAMPLE = {
    "d": "1", "w": "a", "s": " ", "D": "a", "W": "-", "S": "a",
}


def _from_pattern(pattern: str, limit: int = 200) -> str | None:
    """Build one string matching a simple regex.

    Deliberately a subset: literals, escapes, character classes, `.`,
    `{n[,m]}` / `+` / `*` / `?`, groups and top-level alternation (first
    branch wins). Anything else returns None and the caller falls back to its
    candidate list. Contract patterns are things like `^TASK_[0-9]{3}$` and
    `^\\d+\\.\\d+\\.\\d+$`; this covers them without pulling in a solver.
    """
    body = pattern
    if body.startswith("^"):
        body = body[1:]
    if body.endswith("$") and not body.endswith("\\$"):
        body = body[:-1]

    out: list[str] = []
    i = 0
    while i < len(body):
        ch = body[i]
        if len(out) > limit:
            return None

        if ch == "(":
            depth, j = 1, i + 1
            while j < len(body) and depth:
                if body[j] == "\\":
                    j += 2
                    continue
                depth += (body[j] == "(") - (body[j] == ")")
                j += 1
            if depth:
                return None
            inner = body[i + 1:j - 1]
            for prefix in ("?:", "?i:", "?P<"):
                if inner.startswith(prefix):
                    inner = inner[inner.index(">") + 1:] if prefix == "?P<" \
                        else inner[len(prefix):]
                    break
            if inner.startswith("?"):
                return None
            piece = _from_pattern(inner.split("|")[0], limit)
            if piece is None:
                return None
            i = j
        elif ch == "[":
            j = i + 1
            if j < len(body) and body[j] == "^":
                return None
            while j < len(body) and body[j] != "]":
                j += 2 if body[j] == "\\" else 1
            if j >= len(body):
                return None
            cls = body[i + 1:j]
            piece = _sample_class(cls)
            if piece is None:
                return None
            i = j + 1
        elif ch == "\\":
            if i + 1 >= len(body):
                return None
            nxt = body[i + 1]
            piece = _CLASS_SAMPLE.get(nxt, nxt)
            i += 2
        elif ch == ".":
            piece = "a"
            i += 1
        elif ch in "|":
            break  # top-level alternation: the first branch is enough
        elif ch in "*+?{})]":
            return None  # a quantifier with nothing to quantify
        else:
            piece = ch
            i += 1

        # quantifier attached to the piece just built
        count = 1
        if i < len(body):
            q = body[i]
            if q == "?":
                count, i = 1, i + 1
            elif q == "*":
                count, i = 1, i + 1
            elif q == "+":
                count, i = 1, i + 1
            elif q == "{":
                close = body.find("}", i)
                if close == -1:
                    return None
                spec = body[i + 1:close]
                low = spec.split(",")[0].strip() or "1"
                if not low.isdigit():
                    return None
                count, i = max(int(low), 1), close + 1
            if i < len(body) and body[i] == "?":
                i += 1  # non-greedy marker, no effect on a sample
        out.append(piece * count)

    value = "".join(out)
    try:
        if re.search(pattern, value):
            return value
    except re.error:
        return None
    return None


def _sample_class(cls: str) -> str | None:
    """One character satisfying a `[...]` class body."""
    i = 0
    while i < len(cls):
        if cls[i] == "\\" and i + 1 < len(cls):
            return _CLASS_SAMPLE.get(cls[i + 1], cls[i + 1])
        if i + 2 < len(cls) and cls[i + 1] == "-":
            return cls[i]
        if cls[i] != "-":
            return cls[i]
        i += 1
    return None


def _synth_string(node: dict, key: str) -> str | None:
    if "const" in node:
        return node["const"] if isinstance(node["const"], str) else str(node["const"])
    if node.get("enum"):
        first = node["enum"][0]
        return first if isinstance(first, str) else str(first)
    fmt = node.get("format")
    seeds: list[str] = []
    if fmt == "date-time":
        seeds.append("2026-01-01T00:00:00Z")
    elif fmt == "date":
        seeds.append("2026-01-01")
    elif fmt == "email":
        seeds.append("owner@example.com")
    elif fmt in ("uri", "uri-reference"):
        seeds.append("https://example.com/doc")
    if key == "owner":
        seeds.append("owner@example.com")
    seeds.append(f"example-{key}" if key else "example")
    seeds.extend(_PATTERN_CANDIDATES)

    pattern = node.get("pattern")
    low = node.get("minLength")
    high = node.get("maxLength")
    for seed in seeds:
        value = seed
        if isinstance(low, int) and len(value) < low:
            value = (value + "x" * low)[:max(low, len(value))]
        if isinstance(high, int) and len(value) > high:
            value = value[:high]
        if isinstance(low, int) and len(value) < low:
            continue
        if pattern and not re.search(pattern, value):
            continue
        if fmt in ("date-time", "date", "email", "uri", "uri-reference") and seed != seeds[0]:
            continue
        if not value.strip() or value.strip().lower() in {"tbd", "todo", "n/a"}:
            continue
        return value

    # No canned candidate fits: build one from the pattern itself.
    if pattern:
        built = _from_pattern(pattern)
        if built and built.strip():
            if isinstance(low, int) and len(built) < low:
                return None
            if isinstance(high, int) and len(built) > high:
                return None
            return built
    return None


def synth(node: Any, key: str = "") -> Any:
    """Build a value satisfying one schema node, or raise CannotSynth."""
    if not isinstance(node, dict):
        return f"example-{key}" if key else "example"
    if "const" in node:
        return node["const"]
    if node.get("enum"):
        return node["enum"][0]
    declared = node.get("type")
    if isinstance(declared, list):
        declared = next((t for t in declared if t != "null"), declared[0])

    if declared == "object" or (declared is None and node.get("properties")):
        out: dict[str, Any] = {}
        props = node.get("properties") or {}
        for name in node.get("required") or []:
            out[name] = synth(props.get(name, {"type": "string"}), name)
        for name, sub in props.items():
            if name not in out and len(out) < 24:
                out[name] = synth(sub, name)
        if not out:
            out = {"example": "value"}
        return out
    if declared == "array":
        item = node.get("items")
        count = max(1, int(node.get("minItems") or 1))
        count = min(count, int(node.get("maxItems") or count))
        element = synth(item, key) if isinstance(item, dict) else f"item-{key or 'x'}"
        return [element for _ in range(count)]
    if declared == "integer":
        low = node.get("minimum", node.get("exclusiveMinimum", 1))
        value = int(low) + (1 if "exclusiveMinimum" in node else 0)
        high = node.get("maximum")
        if isinstance(high, (int, float)) and value > high:
            value = int(high)
        return value
    if declared == "number":
        low = node.get("minimum", node.get("exclusiveMinimum", 1))
        value = float(low) + (1.0 if "exclusiveMinimum" in node else 0.0)
        high = node.get("maximum")
        if isinstance(high, (int, float)) and value > high:
            value = float(high)
        return value
    if declared == "boolean":
        return True
    if declared == "null":
        return None
    value = _synth_string(node, key)
    if value is None:
        raise CannotSynth(f"cannot build a string satisfying {node!r}")
    return value


class CannotSynth(Exception):
    pass


def build_ok(schema: dict, example: Any, smoke: Any, validate_fn) -> tuple[Any, str]:
    """Pick the OK fixture: the contract's own valid example when it satisfies
    the schema, a repaired version when it nearly does, a synthesised one
    otherwise. Returns (fixture, provenance)."""
    for candidate, origin in ((example, "contract example"),
                              (smoke, "templates/_smoke-test.json")):
        if isinstance(candidate, dict) and not validate_fn(candidate):
            return candidate, origin

    for candidate, origin in ((example, "contract example, repaired"),
                              (smoke, "_smoke-test.json, repaired")):
        if not isinstance(candidate, dict):
            continue
        try:
            repaired = _repair(candidate, schema)
        except CannotSynth:
            continue
        if not validate_fn(repaired):
            return repaired, origin

    fixture = synth(schema)
    if validate_fn(fixture):
        raise CannotSynth(
            f"synthesised fixture still fails its own schema: {validate_fn(fixture)!r}"
        )
    return fixture, "synthesised from schema"


def _repair(obj: dict, schema: dict) -> dict:
    """Fill missing required keys and drop keys the schema forbids."""
    out = dict(obj)
    props = schema.get("properties") or {}
    for name in schema.get("required") or []:
        if name not in out:
            out[name] = synth(props.get(name, {"type": "string"}), name)
    if schema.get("additionalProperties") is False:
        out = {k: v for k, v in out.items() if k in props}
        for name in schema.get("required") or []:
            if name not in out:
                out[name] = synth(props.get(name, {"type": "string"}), name)
    for name, sub in props.items():
        if name in out and isinstance(sub, dict) and sub.get("type") == "object" \
                and isinstance(out[name], dict):
            out[name] = _repair(out[name], sub)
    return out


# --------------------------------------------------------------------------
# mutation — the BAD fixture
# --------------------------------------------------------------------------

def _set_path(obj: Any, path: list, value: Any) -> Any:
    """Return a deep copy of obj with path set to value."""
    clone = json.loads(json.dumps(obj))
    cur = clone
    for step in path[:-1]:
        cur = cur[step]
    cur[path[-1]] = value
    return clone


def _del_path(obj: Any, path: list) -> Any:
    clone = json.loads(json.dumps(obj))
    cur = clone
    for step in path[:-1]:
        cur = cur[step]
    del cur[path[-1]]
    return clone


def _resolve(ok: Any, dotted: str) -> tuple[list, Any] | None:
    """Turn a schema path such as `a.b[]` into a concrete key path into OK."""
    keys: list = []
    cur = ok
    for part in dotted.split("."):
        if not part:
            continue
        array_depth = 0
        while part.endswith("[]"):
            part, array_depth = part[:-2], array_depth + 1
        if not isinstance(cur, dict) or part not in cur:
            return None
        keys.append(part)
        cur = cur[part]
        for _ in range(array_depth):
            if not isinstance(cur, list) or not cur:
                return None
            keys.append(0)
            cur = cur[0]
    return keys, cur


# (priority, category, label) — the earlier a mutation appears the more it
# proves; `required` is last because presence is what the weak validators
# already check.
def mutations(schema: dict, ok: Any):
    """Yield (category, description, expect_substring, mutated_fixture)."""
    plans: list[tuple[int, str, str, str, Any]] = []

    for dotted, node in walk_schema(schema):
        if not dotted:
            continue
        resolved = _resolve(ok, dotted)
        if resolved is None:
            continue
        keys, current = resolved

        enum = node.get("enum")
        if enum:
            bad = "__not_in_enum__"
            while bad in enum:
                bad += "x"
            plans.append((0, "enum", f"{dotted} outside its enum",
                          "not in allowed enum", _set_path(ok, keys, bad)))

        if "const" in node:
            fixed = node["const"]
            bad = "__not_the_const__" if not isinstance(fixed, str) else fixed + "-x"
            plans.append((0, "enum", f"{dotted} away from its const",
                          "is not the required const", _set_path(ok, keys, bad)))

        pattern = node.get("pattern")
        if pattern and isinstance(current, str):
            for bad in ("!!!not-a-match!!!", "@@@", "zzzz-9999"):
                if not re.search(pattern, bad):
                    plans.append((1, "pattern", f"{dotted} against its pattern",
                                  "does not match pattern",
                                  _set_path(ok, keys, bad)))
                    break

        fmt = node.get("format")
        if fmt in ("date-time", "date", "email", "uri") and isinstance(current, str):
            plans.append((2, "pattern", f"{dotted} malformed as {fmt}",
                          f"is not a valid {fmt}",
                          _set_path(ok, keys, "not-a-valid-value")))

        if isinstance(current, (int, float)) and not isinstance(current, bool):
            if isinstance(node.get("minimum"), (int, float)):
                plans.append((3, "numeric", f"{dotted} below its minimum",
                              "is below minimum",
                              _set_path(ok, keys, node["minimum"] - 1)))
            if isinstance(node.get("maximum"), (int, float)):
                plans.append((3, "numeric", f"{dotted} above its maximum",
                              "is above maximum",
                              _set_path(ok, keys, node["maximum"] + 1)))

        if isinstance(current, str):
            low = node.get("minLength")
            if isinstance(low, int) and low > 1:
                plans.append((4, "length", f"{dotted} under its minLength",
                              "is under minLength",
                              _set_path(ok, keys, "x" * (low - 1))))
            high = node.get("maxLength")
            if isinstance(high, int):
                plans.append((4, "length", f"{dotted} over its maxLength",
                              "is over maxLength",
                              _set_path(ok, keys, "x" * (high + 1))))

        if isinstance(current, list):
            low = node.get("minItems")
            if isinstance(low, int) and low >= 1:
                plans.append((5, "items", f"{dotted} under its minItems",
                              "is under minItems",
                              _set_path(ok, keys, [])))
            high = node.get("maxItems")
            if isinstance(high, int):
                plans.append((5, "items", f"{dotted} over its maxItems",
                              "is over maxItems",
                              _set_path(ok, keys, [current[0] if current else "x"] * (high + 1))))

        declared = node.get("type")
        if "const" in node:
            declared = None
        if declared == "string" and isinstance(current, str) and not node.get("enum"):
            plans.append((6, "type", f"{dotted} typed as a number",
                          "expected type", _set_path(ok, keys, 12345)))
        elif declared in ("integer", "number") and not node.get("enum"):
            plans.append((6, "type", f"{dotted} typed as a string",
                          "expected type", _set_path(ok, keys, "not-a-number")))
        elif declared == "array":
            plans.append((6, "type", f"{dotted} typed as a string",
                          "expected type", _set_path(ok, keys, "not-a-list")))

    if schema.get("additionalProperties") is False and isinstance(ok, dict):
        plans.append((7, "unknown", "an undeclared top-level field",
                      "unknown field", {**ok, "__undeclared__": "x"}))

    if isinstance(ok, dict) and isinstance(ok.get("owner"), str):
        plans.append((8, "placeholder", "owner set to a generic group",
                      "generic group", {**ok, "owner": "team"}))

    for name in schema.get("required") or []:
        if isinstance(ok, dict) and name in ok and isinstance(ok[name], str):
            plans.append((9, "placeholder", f"{name} left as TBD",
                          "is a placeholder", {**ok, name: "TBD"}))
            break

    for name in schema.get("required") or []:
        if isinstance(ok, dict) and name in ok:
            plans.append((10, "required", f"{name} missing",
                          "missing required field", _del_path(ok, [name])))
            break

    plans.sort(key=lambda p: p[0])
    for _, category, description, expect, fixture in plans:
        yield category, description, expect, fixture


# --------------------------------------------------------------------------
# code generation
# --------------------------------------------------------------------------

def _pyliteral(obj: Any, indent: int = 0) -> str:
    """Deterministic, diff-stable literal. json.dumps then fix the three
    tokens Python spells differently."""
    text = json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=False)
    text = re.sub(r"(?<![\w\"])\btrue\b", "True", text)
    text = re.sub(r"(?<![\w\"])\bfalse\b", "False", text)
    text = re.sub(r"(?<![\w\"])\bnull\b", "None", text)
    if indent:
        pad = " " * indent
        text = "\n".join(pad + line if i else line
                         for i, line in enumerate(text.splitlines()))
    return text


HEADER = '''#!/usr/bin/env python3
"""validate-{slug}.py

Validate a {title} artefact against the JSON Schema declared in
`content/02-output-contract.xml`. Stdlib-only; no external pip deps.

The schema is inlined below rather than imported: `faion get-content`
materialises only this one methodology's `scripts/` on the user's machine, so
a shared helper module would never arrive with it.

Enforced: required · type · enum · pattern · format · minLength / maxLength ·
minItems / maxItems · minimum / maximum · additionalProperties, plus the house
rules a schema cannot state (a required field left empty or still reading TBD /
TODO / FIXME, and `owner` naming a group rather than a person).

Inputs:
    --file PATH       path to artefact JSON
    --self-test       run built-in fixtures
    --help            this message

Exit codes:
    0 = valid
    1 = invalid (violations printed to stderr)
    2 = usage / unreadable / parse error

Generated by scripts/regen-methodology-validators.py from the contract above.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# --- the output contract, inlined ------------------------------------------
SCHEMA = {schema}

REQUIRED = {required}

'''


def render_validator(slug: str, title: str, schema: dict, ok: Any, bad: Any,
                     expect: str, violates: str, ok_origin: str) -> str:
    parts = [
        HEADER.format(
            slug=slug,
            title=title,
            schema=_pyliteral(schema),
            required=_pyliteral(sorted(schema.get("required") or [])),
        ),
        CHECKER_SOURCE,
        "",
        "",
        "# --- fixtures --------------------------------------------------------------",
        f"# OK: {ok_origin}.",
        f"OK = {_pyliteral(ok, 5)}",
        "",
        f"# BAD: OK with exactly one declared constraint violated — {violates}.",
        f"BAD = {_pyliteral(bad, 6)}",
        "",
        f"BAD_VIOLATES = {violates!r}",
        f"BAD_EXPECT = {expect!r}",
        "",
        "",
        TAIL_SOURCE,
        "",
    ]
    return "\n".join(parts)


def exec_module(source: str, name: str) -> dict:
    """Run generated source in a fresh namespace and hand back its globals."""
    namespace: dict[str, Any] = {"__name__": f"_gen_{name}", "__file__": f"{name}.py"}
    exec(compile(source, f"<generated:{name}>", "exec"), namespace)  # noqa: S102
    return namespace


# --------------------------------------------------------------------------
# strength measurement — the refuse-to-weaken gate
# --------------------------------------------------------------------------

# The generic-owner and placeholder words the corpus's own validators use.
# `ast_census` needs this to tell a FORBIDDEN_OWNERS-style vocabulary apart
# from a genuine enum, whatever the constant happens to be called.
_HOUSE_VOCAB = {
    "", "?", "all", "anyone", "as shown", "backlog", "changeme", "client",
    "client team", "data team", "design", "design team", "design-team",
    "engineering", "everyone", "features", "fill_me", "fixme", "n/a", "na",
    "none", "null", "ops", "ops team", "ourselves", "placeholder", "see image",
    "somebody", "someone", "squad", "tbd", "team", "the client", "the group",
    "the squad", "the team", "they", "todo", "unassigned", "us", "we", "wip",
    "xxx",
}


def ast_census(source: str) -> dict[str, int]:
    """Count the constraints an existing validator demonstrably ENFORCES,
    binned into the same categories as schema_census().

    The distinction that matters is guard versus constraint. `if "k" in obj:`
    and `if isinstance(v, str) and ...` are guards — they decide whether a
    check applies, they are not themselves checks. `if "k" not in obj:` and
    `if not isinstance(v, str):` are constraints. Scoring guards inflated the
    old side and refused slugs the generator would have strictly improved.
    """
    cen: dict[str, int] = dict.fromkeys(CATEGORIES, 0)
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return cen

    # A file this generator produced is scored from its inlined SCHEMA, not by
    # heuristics. Every generated file carries the same `_FORMATS` table and
    # the same `re.search` calls in its walker, which the pattern heuristic
    # reads as four constraints no matter what the contract says — so a second
    # run refused every file the first run wrote. Reading the schema back
    # makes the comparison exact and the tool idempotent.
    if GENERATED_MARKER in source:
        for node in tree.body:
            if isinstance(node, ast.Assign) and len(node.targets) == 1 \
                    and isinstance(node.targets[0], ast.Name) \
                    and node.targets[0].id == "SCHEMA":
                try:
                    prior = ast.literal_eval(node.value)
                except (ValueError, SyntaxError, TypeError):
                    break
                if isinstance(prior, dict):
                    return schema_census(prior)
                break
        return cen

    # Module-level constants, so `for k in REQUIRED` can be scored by how many
    # keys REQUIRED actually holds, and an ENUMS mapping by how many fields it
    # constrains.
    seqs: dict[str, list] = {}
    maps: dict[str, dict] = {}
    for node in tree.body:
        if not (isinstance(node, ast.Assign) and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name)):
            continue
        name = node.targets[0].id
        try:
            value = ast.literal_eval(node.value)
        except (ValueError, SyntaxError, TypeError):
            continue
        if isinstance(value, (list, tuple, set, frozenset)):
            seqs[name] = list(value)
        elif isinstance(value, dict):
            maps[name] = value

    required_names = {n for n in seqs if "REQUIRED" in n.upper()
                      or "MANDATORY" in n.upper() or n.upper().endswith("_KEYS")}

    def _is_house_rule(name: str, members: list) -> bool:
        """A generic-owner or placeholder vocabulary, not an enum. Name alone
        is unreliable — the corpus spells it FORBIDDEN_OWNERS, PLURAL_OWNERS,
        COLLAPSED_OWNERS and GENERIC — so membership decides."""
        if any(tag in name.upper() for tag in
               ("FORBIDDEN", "PLACEHOLDER", "PLURAL", "GENERIC", "BANNED",
                "COLLAPSED", "ANON")):
            return True
        words = [m.lower() for m in members if isinstance(m, str)]
        if not words:
            return False
        hits = sum(1 for w in words if w in _HOUSE_VOCAB)
        return hits * 2 >= len(words)

    enum_names = {n for n, members in seqs.items()
                  if n not in required_names and not _is_house_rule(n, members)}
    house_names = {n for n in seqs if n not in required_names
                   and n not in enum_names}
    # An ENUMS-style mapping of field -> allowed values is one enum per entry.
    for name, mapping in maps.items():
        if mapping and all(isinstance(v, (list, tuple, set, frozenset))
                           for v in mapping.values()):
            cen["enum"] += len(mapping)

    for node in ast.walk(tree):
        if isinstance(node, ast.Compare):
            has_notin = any(isinstance(op, ast.NotIn) for op in node.ops)
            has_member = any(isinstance(op, (ast.In, ast.NotIn)) for op in node.ops)
            # presence: `"key" not in obj` — `"key" in obj` is a guard.
            if has_notin and isinstance(node.left, ast.Constant) \
                    and isinstance(node.left.value, str):
                cen["required"] += 1
            # enum: membership against a named sequence or an inline literal.
            if has_member and not (isinstance(node.left, ast.Constant)
                                   and isinstance(node.left.value, str)):
                for comp in node.comparators:
                    if isinstance(comp, ast.Name) and comp.id in enum_names:
                        cen["enum"] += 1
                    elif isinstance(comp, (ast.Set, ast.List, ast.Tuple)):
                        # `v in (None, "", [], {})` is the house emptiness
                        # idiom, not an enum. An enum is two or more non-empty
                        # scalars.
                        try:
                            members = list(ast.literal_eval(comp))
                        except (ValueError, SyntaxError, TypeError):
                            continue
                        if any(m in (None, "", [], {}) for m in members):
                            cen["placeholder"] += 1
                        elif len(members) >= 2 and all(
                                isinstance(m, (str, int)) and m != "" for m in members):
                            cen["enum"] += 1
            # the generic-owner / placeholder rule
            for comp in node.comparators:
                if isinstance(comp, ast.Name) and comp.id in house_names:
                    cen["placeholder"] += 1
            # length and numeric bounds
            if any(isinstance(op, (ast.Lt, ast.LtE, ast.Gt, ast.GtE))
                   for op in node.ops):
                operands = [node.left, *node.comparators]
                is_len = any(isinstance(o, ast.Call) and isinstance(o.func, ast.Name)
                             and o.func.id == "len" for o in operands)
                if is_len:
                    cen["size"] += 1
                elif any(isinstance(o, ast.Constant) and isinstance(o.value, (int, float))
                         and not isinstance(o.value, bool) for o in operands):
                    cen["numeric"] += 1

        # presence via a loop over a REQUIRED-ish list
        if isinstance(node, ast.For) and isinstance(node.iter, ast.Name) \
                and node.iter.id in required_names:
            cen["required"] += len(seqs[node.iter.id])

        # `not isinstance(...)` is a type constraint; a bare isinstance is a guard.
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not) \
                and isinstance(node.operand, ast.Call) \
                and isinstance(node.operand.func, ast.Name) \
                and node.operand.func.id == "isinstance":
            cen["type"] += 1

        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            attr = node.func.attr
            if attr == "compile" and isinstance(node.func.value, ast.Name) \
                    and node.func.value.id == "re":
                cen["pattern"] += 1
            elif attr in ("match", "search", "fullmatch"):
                cen["pattern"] += 1

    # `re.compile` at module level plus its `.match` in validate() is one
    # constraint counted twice.
    cen["pattern"] = (cen["pattern"] + 1) // 2
    # Placeholder rules are a fixed set on the new side; cap the old side the
    # same way so the two are comparable.
    cen["placeholder"] = min(cen["placeholder"], 3)
    return cen


def probe_old(script: Path, fixture: Any, timeout: float = 20.0) -> int | None:
    """Run the on-disk validator against a fixture. 0 accept, 1 reject,
    None if it could not be run meaningfully.

    The corpus is not consistent about how a validator takes its artefact:
    1,959 declare `--file`, 200 take a bare positional path. Probing only
    `--file` made every one of those 200 exit 2, which reads as "inconclusive"
    and silently drops the behavioural half of the safety net. Both forms are
    tried before giving up.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as fh:
        json.dump(fixture, fh)
        path = fh.name
    try:
        for argv in (["--file", path], [path]):
            try:
                proc = subprocess.run(
                    [sys.executable, str(script), *argv],
                    capture_output=True, text=True, timeout=timeout,
                )
            except (subprocess.TimeoutExpired, OSError):
                return None
            if proc.returncode in (0, 1):
                return proc.returncode
    finally:
        Path(path).unlink(missing_ok=True)
    return None


def alien_probes(ok: Any) -> list[tuple[str, Any]]:
    """Type-preserving substitutions on every top-level field.

    The schema-derived mutations only ever exercise constraints the contract
    declares, so they are blind to the common case: a validator that pins a
    semver, a date or the slug itself while the schema says nothing but
    `"type": "string"`. Swapping in an alien-but-well-typed value surfaces
    exactly those undeclared rules.
    """
    out: list[tuple[str, Any]] = []
    if not isinstance(ok, dict):
        return out
    for key, value in ok.items():
        if isinstance(value, bool):
            alien: Any = not value
        elif isinstance(value, str):
            alien = "zzz-probe-value"
        elif isinstance(value, int):
            alien = 424242
        elif isinstance(value, float):
            alien = 424242.5
        elif isinstance(value, list):
            alien = ["zzz-probe-value"]
        elif isinstance(value, dict):
            continue  # a nested object is covered by its own schema walk
        else:
            continue
        out.append((f"an undeclared rule on {key}", {**ok, key: alien}))
    return out


def behavioural_weaker(script: Path, ok: Any, probes: list,
                       new_validate) -> tuple[bool, list[str]]:
    """Probes the new validator ACCEPTS are the only ones that can expose a
    regression. Sound only when the old validator accepts the base fixture —
    otherwise it rejects every mutation for an unrelated reason, and the
    comparison says nothing.

    Stops at the first loss: one is enough to refuse the slug, and each probe
    costs a subprocess.

    Returns (conclusive, losses). `conclusive` is False when the old validator
    would not accept its own valid artefact — then it rejects every probe for
    an unrelated reason and only the static census is guarding the slug, which
    the report has to say out loud rather than imply.
    """
    if probe_old(script, ok) != 0:
        return False, []
    for description, fixture in probes:
        if new_validate(fixture):
            continue  # new rejects it too — no regression possible
        if probe_old(script, fixture) == 1:
            return True, [description]
    return True, []


# --------------------------------------------------------------------------
# per-slug driver
# --------------------------------------------------------------------------

class Result:
    __slots__ = ("slug", "domain", "status", "detail", "old_cen", "new_cen",
                 "source", "script")

    def __init__(self, slug, domain, status, detail="", old_cen=None,
                 new_cen=None, source=None, script=None):
        self.slug = slug
        self.domain = domain
        self.status = status
        self.detail = detail
        self.old_cen = old_cen or {}
        self.new_cen = new_cen or {}
        self.source = source
        self.script = script

    def gains(self) -> str:
        bits = []
        for cat in CATEGORIES:
            delta = self.new_cen.get(cat, 0) - self.old_cen.get(cat, 0)
            if delta > 0:
                bits.append(f"+{delta} {cat}")
        return ", ".join(bits) or "no net gain"


def process(meth_dir: Path, deep_probe: bool = True,
            allow_static_only: bool = False) -> Result:
    domain, slug = meth_dir.parent.name, meth_dir.name
    contract = meth_dir / "content" / "02-output-contract.xml"
    script = meth_dir / "scripts" / f"validate-{slug}.py"

    if not contract.is_file():
        return Result(slug, domain, "no-contract")
    parsed = read_contract(contract)
    schema = parsed["schema"]
    if not isinstance(schema, dict) or not (schema.get("properties")
                                            or schema.get("required")):
        return Result(slug, domain, "no-schema",
                      "; ".join(parsed["notes"]) or "no JSON Schema in the contract")
    if not script.is_file():
        return Result(slug, domain, "no-validator",
                      f"missing scripts/validate-{slug}.py")

    exotic = unsupported_keywords(schema)
    new_cen = schema_census(schema)
    old_src = script.read_text(encoding="utf-8", errors="replace")
    old_cen = ast_census(old_src)

    title = (schema.get("title") or slug.replace("-", " ")).strip()

    # A throwaway module to run the checker over candidate fixtures while the
    # fixtures are still being chosen.
    probe_src = render_validator(slug, title, schema, {}, {}, "x", "x", "probe")
    try:
        probe_ns = exec_module(probe_src, slug)
    except Exception as exc:  # noqa: BLE001 — a generated file that will not import
        return Result(slug, domain, "error", f"generated module failed to import: {exc}")
    new_validate = probe_ns["validate"]

    try:
        ok, ok_origin = build_ok(schema, parsed["example"],
                                 load_smoke_test(meth_dir), new_validate)
    except (CannotSynth, RecursionError, TypeError, ValueError) as exc:
        return Result(slug, domain, "no-fixture", str(exc), old_cen, new_cen)

    chosen = None
    probes: list = []
    for category, description, expect, fixture in mutations(schema, ok):
        errs = new_validate(fixture)
        probes.append((description, fixture))
        if chosen is None and errs and any(expect in e for e in errs):
            chosen = (category, description, expect, fixture)
    if chosen is None:
        return Result(slug, domain, "no-mutation",
                      "no declared constraint could be violated distinguishably",
                      old_cen, new_cen)
    probes.extend(alien_probes(ok))

    category, violates, expect, bad = chosen
    source = render_validator(slug, title, schema, ok, bad, expect, violates, ok_origin)

    # The generated file must pass its own self-test before anything else.
    try:
        namespace = exec_module(source, slug)
        if _quiet(namespace["self_test"]) != 0:
            return Result(slug, domain, "error", "generated self-test failed",
                          old_cen, new_cen)
    except Exception as exc:  # noqa: BLE001
        return Result(slug, domain, "error", f"generated self-test raised: {exc}",
                      old_cen, new_cen)

    # --- refuse-to-weaken -------------------------------------------------
    regressions = [f"{cat}: {old_cen[cat]} -> {new_cen[cat]}"
                   for cat in CATEGORIES if old_cen[cat] > new_cen[cat]]
    if regressions:
        return Result(slug, domain, "refused-weaker",
                      "static census regressed — " + "; ".join(regressions),
                      old_cen, new_cen)

    probe_note = "behavioural probe skipped (--no-probe)"
    if deep_probe:
        conclusive, losses = behavioural_weaker(script, ok, probes, new_validate)
        if losses:
            return Result(
                slug, domain, "refused-weaker",
                "existing validator rejects what the new one accepts: "
                + "; ".join(losses[:4]),
                old_cen, new_cen,
            )
        if not conclusive and not allow_static_only:
            # The old validator will not accept its own valid artefact, so
            # every probe comes back rejected for an unrelated reason and the
            # differential proves nothing. "Cannot prove not-weaker" is not
            # "not weaker": measured on infra/terraform-state, the unprovable
            # case hid a real cross-field rule (`rationale` must cite an
            # `inputs_used.name`) that no JSON Schema can express and the
            # generator would have silently dropped.
            return Result(slug, domain, "unprovable",
                          "existing validator rejects the contract's own valid "
                          "example, so it cannot be differentially probed; "
                          "static census alone cannot prove the rewrite is not "
                          "weaker (override with --allow-static-only)",
                          old_cen, new_cen)
        probe_note = ("behavioural probe clean" if conclusive else
                      "STATIC GUARD ONLY, forced with --allow-static-only")

    # Nothing gained is churn: rewriting a file to score the same helps no one
    # and enlarges the diff a reviewer has to read.
    if not any(new_cen[c] > old_cen[c] for c in CATEGORIES):
        return Result(slug, domain, "no-gain",
                      "existing validator already matches the contract's census",
                      old_cen, new_cen)

    declares = declared_keywords(schema)
    detail = (f"OK from {ok_origin}; BAD violates a {category} constraint "
              f"({violates})")
    if declares:
        detail += ("; contract declares "
                   + ", ".join(f"{k} x{v}" for k, v in sorted(declares.items())))
    if exotic:
        detail += f"; unsupported keywords ignored: {sorted(exotic)}"
    detail += f"; {probe_note}"
    return Result(slug, domain, "would-write", detail, old_cen, new_cen,
                  source, script)


# --------------------------------------------------------------------------
# the generator's own tests
# --------------------------------------------------------------------------

_T_SCHEMA = {
    "type": "object",
    "required": ["artefact_id", "owner", "status", "items", "score"],
    "properties": {
        "artefact_id": {"type": "string", "minLength": 3},
        "owner": {"type": "string", "format": "email"},
        "status": {"type": "string", "enum": ["draft", "approved"]},
        "items": {"type": "array", "minItems": 2, "items": {"type": "string"}},
        "score": {"type": "integer", "minimum": 0, "maximum": 10},
        "version": {"type": "string", "pattern": "^\\d+\\.\\d+\\.\\d+$"},
    },
    "additionalProperties": False,
}


def _quiet(fn, *fn_args):
    """Run a generated module's self_test without its output on our streams."""
    import contextlib
    import io

    sink = io.StringIO()
    with contextlib.redirect_stdout(sink), contextlib.redirect_stderr(sink):
        return fn(*fn_args)


def self_test() -> int:
    failures: list[str] = []

    def check(label: str, cond: bool) -> None:
        if not cond:
            failures.append(label)

    ns = exec_module(
        render_validator("t", "T", _T_SCHEMA, {}, {}, "x", "x", "t"), "t")
    validate = ns["validate"]

    good = synth(_T_SCHEMA)
    check(f"synth produces a valid fixture ({validate(good)!r})", not validate(good))

    check("enum violation caught",
          any("not in allowed enum" in e
              for e in validate({**good, "status": "nope"})))
    check("minItems violation caught",
          any("under minItems" in e for e in validate({**good, "items": []})))
    check("minimum violation caught",
          any("below minimum" in e for e in validate({**good, "score": -1})))
    check("maximum violation caught",
          any("above maximum" in e for e in validate({**good, "score": 99})))
    check("minLength violation caught",
          any("under minLength" in e for e in validate({**good, "artefact_id": "ab"})))
    check("pattern violation caught",
          any("does not match pattern" in e
              for e in validate({**good, "version": "not-semver"})))
    check("format violation caught",
          any("is not a valid email" in e for e in validate({**good, "owner": "nope"})))
    check("type violation caught",
          any("expected type" in e for e in validate({**good, "score": "ten"})))
    check("additionalProperties caught",
          any("unknown field" in e for e in validate({**good, "zzz": 1})))
    check("missing required caught",
          any("missing required field" in e
              for e in validate({k: v for k, v in good.items() if k != "owner"})))
    check("generic owner caught",
          any("generic group" in e for e in validate({**good, "owner": "team"})))
    check("placeholder caught",
          any("is a placeholder" in e
              for e in validate({**good, "artefact_id": "TBD"})))
    check("non-object rejected", bool(validate(["not", "an", "object"])))

    # The BAD fixture must violate a *declared* constraint, not merely presence.
    muts = list(mutations(_T_SCHEMA, good))
    check("mutations are generated", bool(muts))
    # Explicitly `bool(muts) and ...` — leaning on `muts and ...` would pass a
    # list where a bool is expected and only work by truthiness accident.
    check("first mutation is not a presence check",
          bool(muts) and muts[0][0] != "required")

    # A generated file must pass its own self-test, and its BAD must be
    # rejected for the stated reason.
    category, violates, expect, bad = muts[0]
    check(f"first mutation is a declared constraint, not a house rule "
          f"({category})", category in ("enum", "pattern", "numeric", "length",
                                        "items", "type", "unknown"))
    src = render_validator("t", "T", _T_SCHEMA, good, bad, expect, violates, "synth")
    gen = exec_module(src, "t2")
    check("generated self-test passes", _quiet(gen["self_test"]) == 0)
    check("generated BAD is not OK", gen["BAD"] != gen["OK"])

    # A self-test that would be circular must fail: swap in a BAD that only
    # trips presence while BAD_EXPECT names the enum rule.
    circular = render_validator("t", "T", _T_SCHEMA, good, {}, expect, violates, "synth")
    circ = exec_module(circular, "t3")
    check("circular fixture is rejected by the harness",
          _quiet(circ["self_test"]) == 1)

    # The regex sampler must produce strings that actually match.
    for pattern in (r"^TASK_[0-9]{3}$", r"^\d+\.\d+\.\d+$", r"^[A-Z]{2,4}-\d+$",
                    r"^(draft|final)$", r"^[a-z0-9-]+$"):
        built = _from_pattern(pattern)
        check(f"sampler builds a match for {pattern} (got {built!r})",
              bool(built) and bool(re.search(pattern, built or "")))

    # Alien probes must cover every top-level field and preserve its type.
    aliens = alien_probes(good)
    check("alien probes cover every top-level field",
          len(aliens) == len([k for k, v in good.items() if not isinstance(v, dict)]))
    for _, fixture in aliens:
        differing = [k for k in good if fixture[k] != good[k]]
        check("an alien probe changes exactly one field", len(differing) == 1)

    # Idempotency: re-censusing a file this generator wrote must reproduce the
    # schema's own census exactly, or a second run refuses everything the
    # first run wrote.
    generated = render_validator("t", "T", _T_SCHEMA, good, bad, expect, violates, "s")
    check(f"generated file re-censuses to its own schema "
          f"({ast_census(generated)} vs {schema_census(_T_SCHEMA)})",
          ast_census(generated) == schema_census(_T_SCHEMA))
    check("a generated file is recognised as generated",
          GENERATED_MARKER in generated)

    # AST census: a presence-only validator must score below the schema.
    weak = (
        "REQUIRED = ['artefact_id', 'owner', 'status', 'items', 'score']\n"
        "def validate(obj):\n"
        "    errs = []\n"
        "    for k in REQUIRED:\n"
        "        if k not in obj:\n"
        "            errs.append(k)\n"
        "    return errs\n"
    )
    weak_cen = ast_census(weak)
    new_cen = schema_census(_T_SCHEMA)
    check(f"weak validator scores no enum ({weak_cen})", weak_cen["enum"] == 0)
    check("schema census beats the weak validator",
          all(new_cen[c] >= weak_cen[c] for c in CATEGORIES))

    # A strong validator the schema cannot match must be refused.
    strong = (
        "import re\n"
        "P1 = re.compile('a')\nP2 = re.compile('b')\nP3 = re.compile('c')\n"
        "P4 = re.compile('d')\nP5 = re.compile('e')\nP6 = re.compile('f')\n"
        "def validate(obj):\n"
        "    return [p for p in (P1, P2, P3, P4, P5, P6) if not p.match(str(obj))]\n"
    )
    strong_cen = ast_census(strong)
    check(f"strong validator out-scores this schema on pattern ({strong_cen})",
          strong_cen["pattern"] > new_cen["pattern"])

    # Contract extraction against the corpus's reference case.
    ref = (KNOWLEDGE / "dev" / "diagram-as-code-mermaid-structurizr"
           / "content" / "02-output-contract.xml")
    if ref.is_file():
        parsed = read_contract(ref)
        check("reference contract yields a schema",
              isinstance(parsed["schema"], dict)
              and "diagrams" in (parsed["schema"].get("properties") or {}))
        check("reference contract yields the valid example",
              isinstance(parsed["example"], dict)
              and parsed["example"].get("owner") == "ruslan@faion.net")

    for f in failures:
        sys.stderr.write(f"self-test FAIL: {f}\n")
    if failures:
        return 1
    sys.stdout.write("self-test OK\n")
    return 0


# --------------------------------------------------------------------------
# cli
# --------------------------------------------------------------------------

def discover(domains: list[str], slugs: list[str]) -> list[Path]:
    out: list[Path] = []
    for meta in sorted(KNOWLEDGE.glob("*/*/meta.json")):
        meth = meta.parent
        if domains and meth.parent.name not in domains:
            continue
        if slugs and meth.name not in slugs:
            continue
        out.append(meth)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--slug", action="append", default=[],
                    help="scope to this methodology slug (repeatable)")
    ap.add_argument("--domain", action="append", default=[],
                    help="scope to this knowledge domain (repeatable)")
    ap.add_argument("--write", action="store_true",
                    help="write the regenerated validators (default: dry-run)")
    ap.add_argument("--dry-run", action="store_true", default=False,
                    help="report only; this is the default")
    ap.add_argument("--allow-static-only", action="store_true",
                    help="write even when the existing validator cannot be "
                         "differentially probed because it rejects its own "
                         "valid example (static census guards it alone)")
    ap.add_argument("--no-probe", action="store_true",
                    help="skip the behavioural probe of the existing validator "
                         "(static census only — faster, weaker)")
    ap.add_argument("--verbose", action="store_true",
                    help="one line per slug, whatever the outcome")
    ap.add_argument("--self-test", action="store_true",
                    help="run the generator's own tests")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    if args.write and args.dry_run:
        sys.stderr.write("--write and --dry-run contradict each other\n")
        return 2

    targets = discover(args.domain, args.slug)
    if not targets:
        sys.stderr.write("no methodologies matched the given scope\n")
        return 2
    if args.slug:
        missing = {s for s in args.slug} - {t.name for t in targets}
        for slug in sorted(missing):
            sys.stderr.write(f"unknown slug: {slug}\n")
        if missing:
            return 2

    buckets: dict[str, list[Result]] = {}
    for meth in targets:
        result = process(meth, deep_probe=not args.no_probe,
                         allow_static_only=args.allow_static_only)
        buckets.setdefault(result.status, []).append(result)

        if result.status == "would-write":
            # The write path must not be able to fail half way. A Result can
            # only reach `would-write` with both a target and a rendered
            # source, but the write is guarded rather than assumed: a
            # generator whose whole claim is "it can only strengthen" does not
            # get to crash between opening a file and filling it.
            if result.script is None or not result.source:
                result.status = "error"
                result.detail = "no target path or no rendered source"
                buckets.setdefault("error", []).append(result)
                buckets["would-write"].remove(result)
                print(f"ERROR {result.domain}/{result.slug}: {result.detail}")
                continue
            verb = "WRITE" if args.write else "WOULD-WRITE"
            print(f"{verb} {result.domain}/{result.slug}: {result.gains()}")
            print(f"    {result.detail}")
            if args.write:
                target = result.script
                # Render to a sibling temp file and rename: an interrupted run
                # leaves the original validator intact, never a truncated one.
                tmp = target.with_suffix(".py.regen-tmp")
                tmp.write_text(result.source, encoding="utf-8")
                tmp.chmod(0o755)
                tmp.replace(target)
        elif result.status == "refused-weaker":
            print(f"REFUSED {result.domain}/{result.slug}: {result.detail}")
        elif result.status == "unprovable":
            print(f"UNPROVABLE {result.domain}/{result.slug}: {result.detail}")
        elif args.verbose:
            print(f"{result.status.upper()} {result.domain}/{result.slug}: "
                  f"{result.detail}")

    print("\n--- census " + "-" * 52)
    order = ["would-write", "refused-weaker", "unprovable", "no-gain",
             "no-schema", "no-validator", "no-contract", "no-fixture",
             "no-mutation", "error"]
    for status in order + [s for s in buckets if s not in order]:
        if status in buckets:
            print(f"{status:16s} {len(buckets[status]):5d}")
    print(f"{'total':16s} {len(targets):5d}")
    if not args.write and "would-write" in buckets:
        print("\ndry-run: nothing written. Re-run with --write to apply.")

    problems = (len(buckets.get("error", []))
                + len(buckets.get("refused-weaker", []))
                + len(buckets.get("unprovable", [])))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
