# minimum viable filled-in example of gce-managed-instance-groups.yaml
name: example-name
template: example-template
placement: example-placement
target_size: 1
rolling_update: example-rolling_update
health_check: example-health_check
