#!/usr/bin/env python3
"""playwright-scaffold.py — emit a determinism-hardened Playwright harness into
the caller's own repo, where their venv and their CI own the dependency.

Playwright itself cannot ship inside a tool pack: it needs pip plus a ~150 MB
browser download, and a screenshot is non-deterministic across machines by
default — free-running clocks, animations mid-flight, lazy fonts, a device
scale factor inherited from the host display. So this tool never drives a
browser. It writes the config that removes each of those variables: fixed
viewport per breakpoint, deviceScaleFactor 1, reducedMotion reduce, UTC,
en-US, a pinned colorScheme, a frozen clock, `--font-render-hinting=none`,
an injected animation-kill stylesheet, and a navigation that waits for
networkidle and then asserts the page has settled.

The one variable a config cannot pin is font rasterisation, which follows the
host's installed fonts and FreeType build. `--ci github` therefore pins the
`mcr.microsoft.com/playwright:vX.Y.Z-jammy` container image: same rasteriser
on every runner is the only way a baseline PNG survives a runner upgrade.

It is a pure text transform — no network, no browser, byte-identical output
for identical flags.

Input:  --dir the project root (+ optional shape flags)
Output: <project>/tests/browser/**, optionally .github/workflows/browser-visual.yml
        one summary line on stdout.

Exit: 0 written · 1 refused, files exist and --force was not passed · 2 bad
      input (unknown language, malformed breakpoints, unreadable or invalid
      flows file, unwritable destination).
Zero model calls. Zero network calls.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from pathlib import Path

NAME = "playwright-scaffold"

# Bump together with the repo's own @playwright/test or pytest-playwright pin.
# A container image newer than the installed client rasterises text differently
# and every committed baseline goes red at once.
IMAGE = "mcr.microsoft.com/playwright:v1.49.1-jammy"
FROZEN_CLOCK = "2026-01-01T00:00:00Z"
VIEWPORT_HEIGHT = 900
NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")

# Chromium flags that take font rasterisation and colour management off the
# host's preferences. They narrow the gap between two machines; only the
# pinned container image closes it.
LAUNCH_ARGS = [
    "--font-render-hinting=none",
    "--disable-lcd-text",
    "--force-color-profile=srgb",
    "--hide-scrollbars",
]

ACTIONS = {
    "goto": ("value",),
    "click": ("selector",),
    "fill": ("selector", "value"),
    "press": ("selector", "value"),
    "wait": ("selector",),
    "screenshot": ("value",),
}

OK_FLOWS = (
    '{"name": "signup", "steps": [{"action": "goto", "value": "/signup"},'
    ' {"action": "fill", "selector": "#email", "value": "a@b.c"},'
    ' {"action": "click", "selector": "button[type=submit]"},'
    ' {"action": "screenshot", "value": "signup-done"}], "expect": ".welcome"}\n'
    '{"name": "pricing", "steps": [{"action": "goto", "value": "/pricing"}],'
    ' "expect": "h1"}\n'
)
# The mistake a caller actually makes: an action name the harness has no
# codegen for, silently producing a spec that tests nothing.
BAD_FLOWS = '{"name": "signup", "steps": [{"action": "hover", "selector": "#x"}]}\n'

CSS = """\
/* determinism.css — injected into every page before a screenshot.
   Generated by playwright-scaffold.py; edit freely, it is your repo now. */
*, *::before, *::after {
  animation-delay: -1ms !important;
  animation-duration: 1ms !important;
  animation-iteration-count: 1 !important;
  transition-duration: 1ms !important;
  transition-delay: -1ms !important;
  scroll-behavior: auto !important;
  caret-color: transparent !important;
}
html { -webkit-font-smoothing: antialiased; }
/* Mark anything genuinely volatile (a live clock, a carousel) with this
   attribute rather than widening the diff tolerance. */
[data-volatile] { visibility: hidden !important; }
"""

HARNESS_PY = """\
# harness.py — the settle contract shared by every spec.
# Generated by playwright-scaffold.py; edit freely, it is your repo now.
import pathlib

from playwright.sync_api import Page

BASE_URL = %%BASE_URL%%
BREAKPOINTS = %%BREAKPOINTS%%
FROZEN_CLOCK = %%CLOCK%%
LAUNCH_ARGS = %%ARGS%%
HERE = pathlib.Path(__file__).parent
BASELINE = HERE / %%BASELINE%%
ACTUAL = HERE / "actual"


def settle(page: Page) -> None:
    \"\"\"networkidle is necessary and not sufficient — it says the transport is
    quiet, not that the page stopped moving. Assert the rest explicitly.\"\"\"
    page.wait_for_load_state("networkidle")
    page.wait_for_function("() => document.fonts.status === 'loaded'")
    page.wait_for_function(
        "() => document.getAnimations().every(a => a.playState !== 'running')")
    assert page.evaluate("() => document.readyState") == "complete"


def visit(page: Page, path: str) -> None:
    page.goto(BASE_URL + path, wait_until="networkidle")
    page.add_style_tag(path=str(HERE / "determinism.css"))
    settle(page)


def shoot(page: Page, name: str) -> pathlib.Path:
    \"\"\"Capture only. The comparison is png-diff.py, run as its own gate — a
    screenshot that grades itself has no baseline to disagree with.\"\"\"
    ACTUAL.mkdir(parents=True, exist_ok=True)
    width = page.viewport_size["width"]
    out = ACTUAL / f"{name}-w{width}.png"
    page.screenshot(path=str(out), animations="disabled", caret="hide",
                    scale="css", full_page=True)
    return out
"""

CONFTEST = """\
# conftest.py — determinism-hardened Playwright fixtures.
# Generated by playwright-scaffold.py; edit freely, it is your repo now.
#
# Needs: pip install pytest-playwright && playwright install chromium
import pytest
from playwright.sync_api import Page

from harness import BREAKPOINTS, FROZEN_CLOCK, LAUNCH_ARGS


@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {**browser_type_launch_args, "args": LAUNCH_ARGS}


@pytest.fixture(params=BREAKPOINTS, ids=[f"w{w}" for w in BREAKPOINTS])
def width(request):
    return request.param


@pytest.fixture
def browser_context_args(browser_context_args, width):
    # Every field here is a variable that otherwise follows the host.
    return {
        **browser_context_args,
        "viewport": {"width": width, "height": %%HEIGHT%%},
        "device_scale_factor": 1,
        "reduced_motion": "reduce",
        "timezone_id": "UTC",
        "locale": "en-US",
        "color_scheme": "light",
    }


@pytest.fixture
def page(page: Page):
    # Freeze before the first navigation: a clock installed after load has
    # already let the page read the real time.
    page.clock.install(time=FROZEN_CLOCK)
    page.clock.set_fixed_time(FROZEN_CLOCK)
    yield page
"""

TEST_SCREENS_PY = """\
# test_screens.py — one deterministic capture per screen per breakpoint.
# Generated by playwright-scaffold.py; extend SCREENS, it is your repo now.
import pytest

from harness import shoot, visit

# (name, path). The name becomes baseline/<name>-w<width>.png.
SCREENS = [
    ("home", "/"),
]


@pytest.mark.parametrize("name,path", SCREENS, ids=[s[0] for s in SCREENS])
def test_screen(page, name, path):
    visit(page, path)
    out = shoot(page, name)
    assert out.stat().st_size > 0
"""

FLOW_PY = """\
# %%FILE%% — generated from a --flows line by playwright-scaffold.py.
%%IMPORTS%%


def test_%%FUNC%%(page):
%%BODY%%
"""

CONFIG_TS = """\
// playwright.config.ts — determinism-hardened.
// Generated by playwright-scaffold.py; edit freely, it is your repo now.
import { defineConfig, devices } from '@playwright/test';

const BREAKPOINTS = %%BREAKPOINTS%%;

export default defineConfig({
  testDir: '.',
  fullyParallel: false,
  workers: 1,
  // A retry that turns red into green hides exactly the flake this config
  // exists to remove. Zero, deliberately.
  retries: 0,
  forbidOnly: true,
  reporter: [['line']],
  use: {
    baseURL: %%BASE_URL%%,
    deviceScaleFactor: 1,
    reducedMotion: 'reduce',
    timezoneId: 'UTC',
    locale: 'en-US',
    colorScheme: 'light',
    launchOptions: { args: %%ARGS%% },
  },
  expect: {
    toHaveScreenshot: { animations: 'disabled', caret: 'hide', scale: 'css' },
  },
  projects: BREAKPOINTS.map((w) => ({
    name: `w${w}`,
    use: {
      ...devices['Desktop Chrome'],
      viewport: { width: w, height: %%HEIGHT%% },
      deviceScaleFactor: 1,
    },
  })),
});
"""

DETERMINISM_TS = """\
// determinism.ts — the settle contract shared by every spec.
// Generated by playwright-scaffold.py; edit freely, it is your repo now.
import { Page, expect } from '@playwright/test';
import * as path from 'path';

export const FROZEN_CLOCK = %%CLOCK%%;
export const BASELINE_DIR = %%BASELINE%%;
export const ACTUAL_DIR = 'actual';

export async function freeze(page: Page) {
  // Before the first navigation: a clock installed after load has already
  // let the page read the real time.
  await page.clock.install({ time: FROZEN_CLOCK });
  await page.clock.setFixedTime(new Date(FROZEN_CLOCK));
}

export async function settle(page: Page) {
  // networkidle says the transport is quiet, not that the page stopped
  // moving. Assert the rest explicitly.
  await page.waitForLoadState('networkidle');
  await page.waitForFunction(() => document.fonts.status === 'loaded');
  await page.waitForFunction(() =>
    document.getAnimations().every((a) => a.playState !== 'running'));
  expect(await page.evaluate(() => document.readyState)).toBe('complete');
}

export async function visit(page: Page, url: string) {
  await freeze(page);
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.addStyleTag({ path: path.join(__dirname, 'determinism.css') });
  await settle(page);
}

export async function shoot(page: Page, name: string) {
  // Capture only. The comparison is png-diff.py, run as its own gate.
  const width = page.viewportSize()!.width;
  const out = path.join(__dirname, ACTUAL_DIR, `${name}-w${width}.png`);
  await page.screenshot({ path: out, animations: 'disabled', caret: 'hide',
                          scale: 'css', fullPage: true });
  return out;
}
"""

SCREENS_TS = """\
// screens.spec.ts — one deterministic capture per screen per project.
// Generated by playwright-scaffold.py; extend SCREENS, it is your repo now.
import { test } from '@playwright/test';
import { visit, shoot } from './determinism';

const SCREENS: [string, string][] = [
  ['home', '/'],
];

for (const [name, urlPath] of SCREENS) {
  test(`screen ${name}`, async ({ page }) => {
    await visit(page, urlPath);
    await shoot(page, name);
  });
}
"""

FLOW_TS = """\
// %%FILE%% — generated from a --flows line by playwright-scaffold.py.
%%IMPORTS%%

test(%%TITLE%%, async ({ page }) => {
%%BODY%%
});
"""

WORKFLOW = """\
# browser-visual.yml — generated by playwright-scaffold.py.
#
# The container image is the point. Font rasterisation follows the host's
# FreeType build and installed fonts, so a baseline captured on one runner
# image goes red wholesale on the next. Pinning the image is the only way a
# committed PNG stays comparable. Bump it and the client pin together, and
# re-seed the baselines in the same commit.
name: browser-visual

on: [push, pull_request]

jobs:
  visual:
    runs-on: ubuntu-latest
    container:
      image: %%IMAGE%%
      options: --ipc=host
    steps:
      - uses: actions/checkout@v4
%%SETUP%%
      - name: capture
        run: %%RUN%%
      - name: visual gate
        run: |
          shopt -s nullglob
          baselines=(tests/browser/%%BASELINE%%/*.png)
          if [ ${#baselines[@]} -eq 0 ]; then
            echo "no committed baselines: this job proves nothing"; exit 1
          fi
          fail=0
          for base in "${baselines[@]}"; do
            name=$(basename "$base")
            actual="tests/browser/actual/$name"
            if [ ! -f "$actual" ]; then
              echo "missing capture: $name"; fail=1; continue
            fi
            python3 tests/browser/png-diff.py --a "$base" --b "$actual" \\
              --mask "tests/browser/actual/${name%.png}.mask.png" \\
              --report "tests/browser/actual/${name%.png}.json" || fail=1
          done
          exit $fail
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: browser-actual
          path: tests/browser/actual
"""

SETUP_PY = """\
      - name: install
        run: pip install pytest-playwright
"""
SETUP_TS = """\
      - name: install
        run: npm ci
"""

README = """\
# tests/browser

Determinism-hardened Playwright harness, generated by `playwright-scaffold.py`.
It captures; it does not judge. The gate is `png-diff.py`.

## What is pinned, and why

| Variable | Pinned to | Left free it gives you |
|---|---|---|
| viewport | %%BPLIST%% x %%HEIGHT%% | a layout that follows the window |
| device scale factor | `1` | 2x pixels on a retina dev machine |
| motion | `reduced` + injected CSS | a screenshot mid-transition |
| clock | `%%CLOCK%%` | a rendered timestamp that never repeats |
| timezone / locale | `UTC` / `en-US` | dates and number formats per machine |
| colour scheme | `light` | a dark-mode runner |
| settle | `networkidle` + fonts + animations + `readyState` | a capture before the web font swaps |
| rasteriser | the CI container image | anti-aliasing per host FreeType |

The last row is the one a config cannot fix. Run the suite in
`%%IMAGE%%`, and bump that image and the Playwright
client pin in the same commit as a baseline re-seed.

## Run

```
%%RUNLOCAL%%
```

Captures land in `actual/`. Seed the baselines by copying the files you have
reviewed into `%%BASELINE%%/` and committing them — an empty baseline
directory makes the CI gate fail loudly rather than pass vacuously.

## The gate

`png-diff.py` (faion `browser` tool pack) compares a baseline against a
capture on two gates at once: changed-pixel ratio, which catches drift, and
largest connected cluster, which catches a small structural shift a ratio
hides. Copy it to `tests/browser/png-diff.py` for the CI step to find it.

## Volatile regions

Mark a live clock or a carousel `data-volatile` and the injected stylesheet
hides it. Reach for `png-diff --ignore` only for a region you cannot mark.
Widening `--max-ratio` to absorb a moving element blinds the whole page.
"""


def parse_breakpoints(spec: str) -> list[int] | str:
    """Comma-separated widths, or one error string."""
    widths: list[int] = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk.isdigit():
            return f"--breakpoints must be comma-separated integers, got {chunk!r}"
        value = int(chunk)
        if not 200 <= value <= 4000:
            return f"breakpoint {value} is outside 200-4000"
        widths.append(value)
    if not widths:
        return "--breakpoints is empty"
    if len(set(widths)) != len(widths):
        return "--breakpoints repeats a width"
    return widths


def parse_flows(text: str) -> list[dict] | str:
    """JSONL of {name, steps, expect}, or one error string. Blank and `#` skipped."""
    flows: list[dict] = []
    seen: set[str] = set()
    for lineno, line in enumerate(text.splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            flow = json.loads(line)
        except json.JSONDecodeError as exc:
            return f"flows line {lineno}: not JSON: {exc}"
        if not isinstance(flow, dict):
            return f"flows line {lineno}: not a JSON object"
        name = str(flow.get("name") or "")
        if not NAME_RE.match(name):
            return f"flows line {lineno}: name {name!r} must match {NAME_RE.pattern}"
        if name in seen:
            return f"flows line {lineno}: duplicate flow name {name!r}"
        seen.add(name)
        steps = flow.get("steps")
        if not isinstance(steps, list) or not steps:
            return f"flows line {lineno}: steps must be a non-empty list"
        for index, step in enumerate(steps, 1):
            if not isinstance(step, dict):
                return f"flows line {lineno} step {index}: not a JSON object"
            action = step.get("action")
            if action not in ACTIONS:
                return (f"flows line {lineno} step {index}: unknown action "
                        f"{action!r}; known: {', '.join(sorted(ACTIONS))}")
            for field in ACTIONS[action]:
                if not str(step.get(field) or ""):
                    return (f"flows line {lineno} step {index}: action {action!r} "
                            f"needs {field!r}")
        flows.append(flow)
    if not flows:
        return "flows file holds no flow"
    return flows


def step_py(step: dict) -> str:
    action = step["action"]
    selector = json.dumps(str(step.get("selector") or ""))
    value = json.dumps(str(step.get("value") or ""))
    if action == "goto":
        return f"    visit(page, {value})"
    if action == "click":
        return f"    page.click({selector})"
    if action == "fill":
        return f"    page.fill({selector}, {value})"
    if action == "press":
        return f"    page.press({selector}, {value})"
    if action == "wait":
        return f"    page.wait_for_selector({selector})"
    return f"    shoot(page, {value})"


def step_ts(step: dict) -> str:
    action = step["action"]
    selector = json.dumps(str(step.get("selector") or ""))
    value = json.dumps(str(step.get("value") or ""))
    if action == "goto":
        return f"  await visit(page, {value});"
    if action == "click":
        return f"  await page.click({selector});"
    if action == "fill":
        return f"  await page.fill({selector}, {value});"
    if action == "press":
        return f"  await page.press({selector}, {value});"
    if action == "wait":
        return f"  await page.waitForSelector({selector});"
    return f"  await shoot(page, {value});"


def helpers_used(flow: dict) -> list[str]:
    """Which harness helpers this flow's steps actually reach. An import the
    spec never uses is a lint failure in the caller's repo on day one."""
    actions = {step["action"] for step in flow["steps"]}
    used = []
    if "screenshot" in actions:
        used.append("shoot")
    if "goto" in actions:
        used.append("visit")
    return used


def render(template: str, mapping: dict[str, str]) -> str:
    """Token substitution. Not str.format: every emitted language is full of
    braces, and escaping them all is how a template acquires a typo."""
    out = template
    for key, value in mapping.items():
        out = out.replace(f"%%{key}%%", value)
    return out


def plan(lang: str, base_url: str, widths: list[int], baseline: str,
         ci: str, flows: list[dict]) -> dict[str, str]:
    """Every file the run would write: relative path -> content. Pure, so two
    runs with the same flags are byte-identical and --self-test can prove it."""
    root = "tests/browser"
    args_json = json.dumps(LAUNCH_ARGS)
    common = {
        "BASE_URL": json.dumps(base_url),
        "BREAKPOINTS": json.dumps(widths),
        "BPLIST": "/".join(str(w) for w in widths),
        "CLOCK": json.dumps(FROZEN_CLOCK),
        "BASELINE": baseline,
        "HEIGHT": str(VIEWPORT_HEIGHT),
        "ARGS": args_json,
        "IMAGE": IMAGE,
    }
    run_local = ("pytest tests/browser -q" if lang == "py"
                 else "npx playwright test -c tests/browser/playwright.config.ts")
    files: dict[str, str] = {
        f"{root}/README.md": render(README, {**common, "RUNLOCAL": run_local}),
        f"{root}/determinism.css": CSS,
        f"{root}/{baseline}/.gitkeep": "",
    }

    if lang == "py":
        files[f"{root}/harness.py"] = render(
            HARNESS_PY, {**common, "BASELINE": json.dumps(baseline)})
        files[f"{root}/conftest.py"] = render(CONFTEST, common)
        files[f"{root}/test_screens.py"] = TEST_SCREENS_PY
        for flow in flows:
            func = flow["name"].replace("-", "_")
            filename = f"test_flow_{func}.py"
            body = [step_py(s) for s in flow["steps"]]
            imports = []
            if flow.get("expect"):
                imports.append("from playwright.sync_api import expect")
                imports.append("")
                body.append("    expect(page.locator("
                            f"{json.dumps(str(flow['expect']))})).to_be_visible()")
            used = helpers_used(flow)
            if used:
                imports.append(f"from harness import {', '.join(used)}")
            files[f"{root}/{filename}"] = render(
                FLOW_PY, {"FILE": filename, "FUNC": func,
                          "IMPORTS": "\n".join(imports).rstrip(),
                          "BODY": "\n".join(body)})
    else:
        files[f"{root}/playwright.config.ts"] = render(CONFIG_TS, common)
        files[f"{root}/determinism.ts"] = render(
            DETERMINISM_TS, {**common, "BASELINE": json.dumps(baseline)})
        files[f"{root}/screens.spec.ts"] = SCREENS_TS
        for flow in flows:
            filename = f"flow-{flow['name']}.spec.ts"
            body = [step_ts(s) for s in flow["steps"]]
            names = ["test"]
            if flow.get("expect"):
                names.append("expect")
                body.append("  await expect(page.locator("
                            f"{json.dumps(str(flow['expect']))})).toBeVisible();")
            imports = [f"import {{ {', '.join(names)} }} from '@playwright/test';"]
            used = helpers_used(flow)
            if used:
                imports.append(
                    f"import {{ {', '.join(used)} }} from './determinism';")
            files[f"{root}/{filename}"] = render(
                FLOW_TS, {"FILE": filename,
                          "TITLE": json.dumps(f"flow {flow['name']}"),
                          "IMPORTS": "\n".join(imports),
                          "BODY": "\n".join(body)})

    if ci == "github":
        files[".github/workflows/browser-visual.yml"] = render(WORKFLOW, {
            **common,
            "SETUP": SETUP_PY if lang == "py" else SETUP_TS,
            "RUN": run_local,
        })
    return files


def self_test() -> list[str]:
    """Prove the generator is deterministic and that the flow parser rejects
    the mistake a caller makes. Writes only into a temporary directory."""
    failures: list[str] = []
    widths = parse_breakpoints("390,768,1440")
    if isinstance(widths, str):
        return [f"OK breakpoints rejected: {widths}"]
    for spec in ("390,x", "12", "390,390", ""):
        if not isinstance(parse_breakpoints(spec), str):
            failures.append(f"breakpoints {spec!r} was accepted")

    flows = parse_flows(OK_FLOWS)
    if isinstance(flows, str):
        return [f"OK flows fixture rejected: {flows}"]
    if len(flows) != 2:
        failures.append(f"OK flows fixture parsed {len(flows)} flows, want 2")
    if not isinstance(parse_flows(BAD_FLOWS), str):
        failures.append("BAD flows fixture produced no finding")

    first = plan("py", "http://localhost:3000", widths, "baseline", "github", flows)
    second = plan("py", "http://localhost:3000", widths, "baseline", "github", flows)
    if first != second:
        failures.append("two runs with identical flags differ")
    if "tests/browser/test_flow_signup.py" not in first:
        failures.append("no spec generated for the signup flow")
    if "page.clock.set_fixed_time" not in first["tests/browser/conftest.py"]:
        failures.append("python config does not freeze the clock")
    if IMAGE not in first[".github/workflows/browser-visual.yml"]:
        failures.append("workflow does not pin the container image")

    # A flow that never screenshots must not import shoot: an unused import is
    # a lint failure in the caller's repo on day one.
    pricing = first.get("tests/browser/test_flow_pricing.py", "")
    if "shoot" in pricing or "visit" not in pricing:
        failures.append("python flow spec imports helpers it does not use")

    typescript = plan("ts", "http://x.test", widths, "baseline", "none", flows)
    if "shoot" in typescript.get("tests/browser/flow-pricing.spec.ts", ""):
        failures.append("ts flow spec imports helpers it does not use")
    config = typescript.get("tests/browser/playwright.config.ts", "")
    for needle in ("deviceScaleFactor: 1", "reducedMotion: 'reduce'",
                   "timezoneId: 'UTC'", "colorScheme: 'light'", "retries: 0"):
        if needle not in config:
            failures.append(f"ts config is missing {needle!r}")
    if any(p.startswith(".github/") for p in typescript):
        failures.append("--ci none still emitted a workflow")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for relative, text in first.items():
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
        if not (root / "tests/browser/baseline/.gitkeep").is_file():
            failures.append("baseline/.gitkeep was not written")
        empty = [p for p, t in first.items()
                 if not t.strip() and not p.endswith(".gitkeep")]
        if empty:
            failures.append(f"generated empty files: {empty}")
    return failures


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", help="project root; the harness lands in tests/browser")
    ap.add_argument("--lang", default="py", choices=["py", "ts"],
                    help="pytest-playwright or @playwright/test")
    ap.add_argument("--base-url", default="http://localhost:3000",
                    help="origin the harness navigates against")
    ap.add_argument("--breakpoints", default="390,768,1440",
                    help="comma-separated viewport widths")
    ap.add_argument("--baseline-dir", default="baseline",
                    help="baseline directory, relative to tests/browser")
    ap.add_argument("--ci", default="none", choices=["github", "none"],
                    help="also emit a workflow pinning the Playwright image")
    ap.add_argument("--flows", help="JSONL of {name, steps, expect}, one spec per line")
    ap.add_argument("--force", action="store_true",
                    help="overwrite files that already exist")
    ap.add_argument("--self-test", action="store_true",
                    help="run the built-in fixtures and exit")
    args = ap.parse_args()

    if args.self_test:
        failures = self_test()
        for failure in failures:
            print(f"{NAME}: self-test: {failure}", file=sys.stderr)
        print(f"{NAME}: self-test checks=20 failures={len(failures)}")
        return 1 if failures else 0

    if not args.dir:
        print(f"{NAME}: --dir is required", file=sys.stderr)
        return 2
    project = Path(args.dir)
    if not project.is_dir():
        print(f"{NAME}: --dir is not a directory: {project}", file=sys.stderr)
        return 2

    baseline = args.baseline_dir.strip("/")
    if not baseline or baseline.startswith("/") or ".." in Path(baseline).parts:
        print(f"{NAME}: --baseline-dir must stay under tests/browser",
              file=sys.stderr)
        return 2

    widths = parse_breakpoints(args.breakpoints)
    if isinstance(widths, str):
        print(f"{NAME}: {widths}", file=sys.stderr)
        return 2

    flows: list[dict] = []
    if args.flows:
        try:
            text = Path(args.flows).read_text(encoding="utf-8")
        except OSError as exc:
            print(f"{NAME}: cannot read --flows: {exc}", file=sys.stderr)
            return 2
        parsed = parse_flows(text)
        if isinstance(parsed, str):
            print(f"{NAME}: {parsed}", file=sys.stderr)
            return 2
        flows = parsed

    files = plan(args.lang, args.base_url, widths, baseline, args.ci, flows)
    existing = sorted(p for p in files if (project / p).exists())
    if existing and not args.force:
        print(f"{NAME}: refusing to overwrite {len(existing)} file(s): "
              f"{', '.join(existing[:3])}"
              f"{' …' if len(existing) > 3 else ''} (use --force)",
              file=sys.stderr)
        return 1

    try:
        for relative, text in files.items():
            target = project / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
    except OSError as exc:
        print(f"{NAME}: cannot write into {project}: {exc}", file=sys.stderr)
        return 2

    print(f"{NAME}: lang={args.lang} files={len(files)} "
          f"breakpoints={'/'.join(str(w) for w in widths)} flows={len(flows)} "
          f"ci={args.ci} image={IMAGE} -> {project}/tests/browser")
    return 0


if __name__ == "__main__":
    sys.exit(main())
