# minimum viable filled-in example of gce-instance-templates.yaml
name: example-name
machine_type: example-machine_type
image: example-image
service_account: 1
startup_script: example-startup_script
metadata: example-metadata
