# minimum viable filled-in example of gce-spot-vms.yaml
scheduling: example-scheduling
provisioning_model: example-provisioning_model
instance_termination_action: example-instance_termination_action
checkpoint_target: example-checkpoint_target
